import 'package:flutter/material.dart';

import 'package:starforge_staff/data/models.dart';

abstract final class DemoData {
  static const students = [
    Student(
      id: 's1',
      name: 'Madina Akramova',
      phone: '+998 90 123 45 67',
      guardian: 'Kamola Akramova',
      guardianPhone: '+998 93 221 40 10',
      birthDate: '14 March 2008',
      joinedDate: '12 September 2025',
      attendance: .96,
      lastExam: 88,
      hasSmartCard: true,
    ),
    Student(
      id: 's2',
      name: 'Temur Ismoilov',
      phone: '+998 91 404 12 33',
      guardian: 'Sardor Ismoilov',
      guardianPhone: '+998 91 404 12 30',
      birthDate: '2 November 2007',
      joinedDate: '12 September 2025',
      attendance: .84,
      lastExam: 74,
      state: StudentState.late,
    ),
    Student(
      id: 's3',
      name: 'Dilnoza Hamidova',
      phone: '+998 99 887 62 20',
      guardian: 'Shahnoza Hamidova',
      guardianPhone: '+998 99 887 62 21',
      birthDate: '28 June 2008',
      joinedDate: '18 September 2025',
      attendance: .91,
      lastExam: 82,
    ),
    Student(
      id: 's4',
      name: 'Asadbek Rahmonov',
      phone: '+998 97 330 20 11',
      guardian: 'Zafar Rahmonov',
      guardianPhone: '+998 97 330 20 10',
      birthDate: '9 January 2008',
      joinedDate: '12 September 2025',
      attendance: .77,
      lastExam: 62,
      state: StudentState.absent,
      hasWarningCard: true,
    ),
    Student(
      id: 's5',
      name: 'Malika Yoqubova',
      phone: '+998 90 744 16 89',
      guardian: 'Umida Yoqubova',
      guardianPhone: '+998 90 744 16 80',
      birthDate: '17 August 2007',
      joinedDate: '12 September 2025',
      attendance: .98,
      lastExam: 93,
      hasSmartCard: true,
    ),
    Student(
      id: 's6',
      name: 'Jasur Aliev',
      phone: '+998 95 601 54 80',
      guardian: 'Nargiza Alieva',
      guardianPhone: '+998 95 601 54 81',
      birthDate: '23 May 2008',
      joinedDate: '20 September 2025',
      attendance: .89,
      lastExam: 78,
      state: StudentState.excused,
    ),
    Student(
      id: 's7',
      name: 'Zarina Rustamova',
      phone: '+998 93 208 37 90',
      guardian: 'Bahrom Rustamov',
      guardianPhone: '+998 93 208 37 91',
      birthDate: '6 December 2007',
      joinedDate: '20 September 2025',
      attendance: .94,
      lastExam: 86,
    ),
    Student(
      id: 's8',
      name: 'Said Abduvaliyev',
      phone: '+998 88 920 77 13',
      guardian: 'Murod Abduvaliyev',
      guardianPhone: '+998 88 920 77 10',
      birthDate: '11 April 2008',
      joinedDate: '24 September 2025',
      attendance: .81,
      lastExam: 71,
      state: StudentState.late,
    ),
  ];

  static final groups = [
    LearningGroup(
      id: 'g1',
      name: 'Aurora B2 · 24',
      course: 'General English',
      level: 'Upper Intermediate',
      studyMonth: 3,
      schedule: 'Mon · Wed · Fri  10:00',
      room: 'A–204',
      branch: 'Oybek',
      department: 'English',
      mainTeacher: 'Aziza Karimova',
      progress: .68,
      attendance: .91,
      nextLesson: 'Today · 10:00',
      students: students,
      isExamSoon: true,
    ),
    LearningGroup(
      id: 'g2',
      name: 'Nova IELTS · 11',
      course: 'IELTS Foundation',
      level: 'Pre-IELTS',
      studyMonth: 2,
      schedule: 'Tue · Thu · Sat  15:30',
      room: 'B–102',
      branch: 'Chilonzor',
      department: 'English',
      mainTeacher: 'Aziza Karimova',
      progress: .44,
      attendance: .87,
      nextLesson: 'Tomorrow · 15:30',
      students: students.take(6).toList(),
    ),
    LearningGroup(
      id: 'g3',
      name: 'Orion Teens · 07',
      course: 'English for Teens',
      level: 'Elementary',
      studyMonth: 5,
      schedule: 'Mon · Wed · Fri  17:00',
      room: 'C–305',
      branch: 'Oybek',
      department: 'English',
      mainTeacher: 'Aziza Karimova',
      progress: .82,
      attendance: .93,
      nextLesson: 'Today · 17:00',
      students: students.reversed.take(7).toList(),
    ),
  ];

  static const tasks = [
    StaffTask(
      id: 't1',
      title: 'Review Aurora B2 writing',
      description:
          'Give short feedback on Task 2 drafts before the next lesson.',
      due: 'Today · 16:00',
      assignee: 'Aziza Karimova',
      creator: 'Academic department',
      stage: TaskStage.todo,
      highPriority: true,
      tags: ['Aurora B2', 'Academic'],
    ),
    StaffTask(
      id: 't2',
      title: 'Prepare speaking cards',
      description: 'Create six paired prompts for the teen group.',
      due: 'Tomorrow · 10:00',
      assignee: 'Aziza Karimova',
      creator: 'Aziza Karimova',
      stage: TaskStage.inProgress,
      tags: ['Orion Teens'],
    ),
    StaffTask(
      id: 't3',
      title: 'Upload IELTS listening pack',
      description: 'Publish audio and worksheets for your students.',
      due: '14 Aug',
      assignee: 'Aziza Karimova',
      creator: 'Academic department',
      stage: TaskStage.inProgress,
      tags: ['Library', 'IELTS'],
    ),
    StaffTask(
      id: 't4',
      title: 'Submit July progress notes',
      description: 'Monthly progress notes submitted for all groups.',
      due: 'Completed 8 Aug',
      assignee: 'Aziza Karimova',
      creator: 'Academic department',
      stage: TaskStage.done,
      tags: ['Report'],
    ),
  ];

  static const contacts = [
    ChatContact(
      id: 'c1',
      name: 'Malika Yoqubova',
      role: 'Student · Aurora B2',
      preview: 'Thank you, I will send the homework today.',
      time: '10:42',
      unread: 2,
      online: true,
      isStudent: true,
    ),
    ChatContact(
      id: 'c2',
      name: 'Academic Team',
      role: 'Staff group · 12 members',
      preview: 'Sardor: Meeting moved to 17:30 tomorrow.',
      time: '09:18',
      unread: 5,
      online: true,
    ),
    ChatContact(
      id: 'c3',
      name: 'Kamola Raximova',
      role: 'Reception · Oybek',
      preview: 'The new student will arrive 10 minutes early.',
      time: 'Yesterday',
      online: true,
    ),
    ChatContact(
      id: 'c4',
      name: 'Temur Ismoilov',
      role: 'Student · Aurora B2',
      preview: 'Voice message · 0:18',
      time: 'Yesterday',
      isStudent: true,
    ),
    ChatContact(
      id: 'c5',
      name: 'Print Center · Oybek',
      role: 'Service chat',
      preview: 'Your worksheet set is ready to collect.',
      time: 'Mon',
    ),
    ChatContact(
      id: 'c6',
      name: 'Dilnoza Hamidova',
      role: 'Student · Aurora B2',
      preview: 'Got it, see you Wednesday!',
      time: 'Sun',
      isStudent: true,
      archived: true,
    ),
  ];

  static const chatMessages = [
    ChatMessage(
      id: 'm1',
      text: 'Good morning! I added feedback to your writing draft.',
      time: '10:34',
      isMine: true,
    ),
    ChatMessage(
      id: 'm2',
      text: 'Good morning, teacher. I saw it — the examples helped a lot.',
      time: '10:36',
      isMine: false,
    ),
    ChatMessage(
      id: 'm3',
      text: 'Voice message',
      time: '10:38',
      isMine: false,
      type: MessageType.voice,
      duration: '0:24',
    ),
    ChatMessage(
      id: 'm4',
      text: 'Thank you, I will send the homework today.',
      time: '10:42',
      isMine: false,
    ),
  ];

  static const library = [
    LibraryResource(
      id: 'l1',
      title: 'English File B2',
      subtitle: 'Student book · 168 pages',
      author: 'Academic Library',
      kind: LibraryKind.book,
      color: Color(0xFF4F6DB8),
      icon: Icons.menu_book_rounded,
      progress: .42,
    ),
    LibraryResource(
      id: 'l2',
      title: 'Morning Focus',
      subtitle: '12 tracks · 46 min',
      author: 'Aziza Karimova',
      kind: LibraryKind.playlist,
      color: Color(0xFFB65C79),
      icon: Icons.graphic_eq_rounded,
    ),
    LibraryResource(
      id: 'l3',
      title: 'IELTS Speaking Lab',
      subtitle: 'Episode 8 · Fluency',
      author: 'Starforge Podcast',
      kind: LibraryKind.podcast,
      color: Color(0xFF8060B3),
      icon: Icons.podcasts_rounded,
      downloadable: false,
      progress: .71,
    ),
    LibraryResource(
      id: 'l4',
      title: 'Conditionals, clearly',
      subtitle: 'Video lesson · 14 min',
      author: 'Bekzod Jalolov',
      kind: LibraryKind.video,
      color: Color(0xFF287E7C),
      icon: Icons.play_arrow_rounded,
      downloadable: false,
    ),
    LibraryResource(
      id: 'l5',
      title: 'Vocabulary in Use',
      subtitle: 'Workbook · 104 pages',
      author: 'Academic Library',
      kind: LibraryKind.book,
      color: Color(0xFFC4783D),
      icon: Icons.auto_stories_rounded,
    ),
  ];

  static const printers = [
    PrinterDevice(
      id: 'p1',
      name: 'Atlas · A3 Color',
      location: 'Oybek · 2nd floor',
      toner: .82,
      paper: 'A4 · 214 sheets',
      supportsColor: true,
    ),
    PrinterDevice(
      id: 'p2',
      name: 'Nova · Fast B/W',
      location: 'Oybek · Teacher room',
      toner: .64,
      paper: 'A4 · 98 sheets',
    ),
    PrinterDevice(
      id: 'p3',
      name: 'Orion · A4 Color',
      location: 'Chilonzor · Reception',
      toner: .31,
      paper: 'A4 · 46 sheets',
      isBusy: true,
      supportsColor: true,
    ),
  ];
}
