import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('uz'), Locale('en'), Locale('ru')];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  String tr(String key) {
    final language = locale.languageCode;
    return _values[language]?[key] ?? _values['en']?[key] ?? key;
  }

  String format(String key, Map<String, Object> values) {
    var result = tr(key);
    for (final entry in values.entries) {
      result = result.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return result;
  }

  String count(String key, int count) {
    final suffix = switch (locale.languageCode) {
      'ru' when count % 10 == 1 && count % 100 != 11 => 'One',
      'ru'
          when const {2, 3, 4}.contains(count % 10) &&
              !const {12, 13, 14}.contains(count % 100) =>
        'Few',
      'ru' => 'Many',
      'en' when count == 1 => 'One',
      _ => 'Other',
    };
    return format('$key$suffix', {'count': count});
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appName': 'Starforge Staff',
      'welcomeBack': 'Welcome back',
      'loginSubtitle': 'Your calm, connected workspace.',
      'loginEyebrow': 'STAFF WORKSPACE',
      'loginPromise': 'Plan with clarity. Teach with confidence.',
      'loginDetail':
          'Lessons, students, tasks and conversations — thoughtfully organized for your day.',
      'username': 'Username',
      'password': 'Password',
      'usernameRequired': 'Enter your username.',
      'passwordTooShort': 'Password must be at least 4 characters.',
      'passwordRequired': 'Enter your password.',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'signIn': 'Sign in',
      'forgotPassword': 'Forgot password?',
      'forgotMessage':
          'Please contact your administration team. They will reset your password safely.',
      'privacyPolicy': 'Privacy policy',
      'viewFullPolicy': 'View full policy',
      'policyOpenFailed': 'The policy could not be opened safely. Try again.',
      'terms': 'Staff privacy & terms',
      'termsBody':
          'Starforge protects staff and student information. Access is role-based, activity may be audited, and learning records must only be used for approved education-center work.',
      'role': 'Staff role',
      'teacher': 'Teacher',
      'assistant': 'Assistant',
      'media': 'Media',
      'reception': 'Reception',
      'sales': 'Sales',
      'printer': 'Print specialist',
      'cashier': 'Cashier',
      'staffMember': 'Staff member',
      'invalidLogin': 'The username or password is incorrect.',
      'restrictedLogin':
          'Manager and executive accounts use the Starforge Management app.',
      'loginUnavailable':
          'We could not sign you in just now. Please check your connection and try again.',
      'loginRateLimited':
          'There were several attempts. Please wait a moment, then try again.',
      'roleAuto': 'Your workspace is prepared for your staff account',
      'secureWorkspace': 'Private staff workspace',
      'passwordRequiredTitle': 'Create a new password',
      'passwordRequiredBody':
          'For your protection, choose a new password before continuing.',
      'currentPassword': 'Current password',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm new password',
      'updatePassword': 'Update password',
      'passwordRules': 'Use at least 10 characters.',
      'passwordMismatch': 'The new passwords do not match.',
      'passwordUpdateFailed':
          'We could not update the password. Check the current password and try again.',
      'passwordUpdated': 'Your password was updated.',
      'changesSaved': 'Your changes were saved.',
      'changesCouldNotSave':
          'Your changes could not be saved. Please try again.',
      'warmLogin': 'Good to see you. Everything is ready for a focused day.',
      'home': 'Home',
      'groups': 'Groups',
      'tasks': 'Tasks',
      'messages': 'Messages',
      'profile': 'Profile',
      'workHub': 'Work',
      'workHubTitle': 'Your complete workspace',
      'workHubSubtitle':
          'Students, resources, surveys, requests, recognition, reports and account tools.',
      'workNowTitle': 'Needs attention',
      'workResourcesTitle': 'Tools and records',
      'workAccountTitle': 'Employment and account',
      'assignedStudents': 'My students',
      'assignedStudentsSubtitle': 'Students in your assigned groups only.',
      'formsSurveys': 'Forms & surveys',
      'formsSurveysSubtitle': 'Complete surveys shared with your role.',
      'requests': 'Requests',
      'requestsSubtitle': 'Create and follow workplace requests.',
      'achievements': 'Achievements',
      'achievementsSubtitle': 'Recognize students in your groups.',
      'reports': 'Reports',
      'reportsSubtitle': 'Prepare and share your teaching reports.',
      'goodMorning': 'Good morning',
      'goodAfternoon': 'Good afternoon',
      'goodEvening': 'Good evening',
      'motivation1': 'Small progress, repeated daily, becomes mastery.',
      'motivation2': 'Your calm attention can change a student’s whole day.',
      'motivation3': 'Teach with clarity. Lead with kindness.',
      'motivation4': 'Today is another chance to make learning feel possible.',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'nextLesson': 'Next lesson',
      'room': 'Room',
      'students': 'Students',
      'totalStudents': 'Total students',
      'attendance': 'Attendance',
      'startsIn': 'Starts in {time}',
      'durationHoursMinutes': '{hours} hr {minutes} min',
      'durationMinutes': '{minutes} min',
      'quickActions': 'Quick actions',
      'takeAttendance': 'Take attendance',
      'openTasks': 'Open tasks',
      'library': 'Library',
      'printCenter': 'Print center',
      'important': 'Important',
      'meeting': 'Meeting',
      'meetingsTitle': 'Meetings',
      'meetingsSubtitle': 'Upcoming meetings in your authorized work scope.',
      'meetingsEmpty': 'No upcoming meetings',
      'meetingsEmptyBody':
          'New invitations will appear here when they are scheduled.',
      'meetingsLoadFailed': 'Meetings could not be loaded',
      'meetingPending': 'Awaiting your response',
      'meetingAccepted': 'Accepted',
      'meetingDeclined': 'Declined',
      'acceptMeeting': 'Accept',
      'declineMeeting': 'Decline',
      'meetingResponseSaved': 'Your meeting response was saved.',
      'meetingResponseFailed': 'Your meeting response could not be saved.',
      'schedule': 'Today’s schedule',
      'upcomingSchedule': 'Upcoming schedule',
      'upcoming': 'Upcoming',
      'openAttendance': 'Open attendance',
      'noUpcomingLessons': 'Your upcoming schedule is clear',
      'noUpcomingLessonsBody':
          'New lessons will appear here as soon as they are scheduled.',
      'dashboardNeedsMoment': 'A few updates need another moment.',
      'suggestion': 'Suggestion',
      'academicDepartment': 'Academic department',
      'seeAll': 'See all',
      'aiInsight': 'AI teaching note',
      'aiUnavailable': 'AI is taking a short break. Please check again later.',
      'aiNoRecommendations':
          'AI is available. There is no verified recommendation for you right now.',
      'aiDegraded':
          'AI is taking a little longer than usual, so recommendations are paused for now.',
      'aiStatusUnavailable':
          'We could not check AI right now. Your other tools are still available.',
      'aiStatusChecking': 'Checking AI availability…',
      'featureAvailable': 'Available',
      'featureDegraded': 'Limited',
      'featureUnavailable': 'Paused',
      'featureStatusUnknown': 'Status pending',
      'featureUnavailablePolite':
          'This area is taking a short pause. Please check back a little later.',
      'weeklyPulse': 'Weekly pulse',
      'lessons': 'Lessons',
      'completed': 'Completed',
      'onTime': 'On time',
      'reviewsDue': 'Reviews due',
      'announcements': 'Announcements',
      'noAnnouncements': 'There are no announcements right now.',
      'yourGroups': 'Your groups',
      'groupsSubtitle': 'Only groups assigned to you are visible.',
      'searchGroups': 'Search groups',
      'assignedGroups': 'Assigned groups',
      'groupPortfolio': 'Learning group',
      'capacity': 'Capacity',
      'refresh': 'Refresh',
      'tryAgain': 'Try again',
      'search': 'Search',
      'clear': 'Clear',
      'noItems': 'Nothing here yet',
      'noAssignedGroups': 'A clear space for what comes next',
      'noAssignedGroupsBody':
          'Your assigned groups will appear here as soon as they are ready.',
      'groupsLoadFailed': 'Your groups need a moment',
      'groupsLoadFailedBody':
          'Please check your connection, then try once more.',
      'studentListPreparing': 'Preparing the latest class list',
      'noStudentsYet': 'A fresh class list',
      'noStudentsYetBody': 'Students enrolled in this group will appear here.',
      'attendanceNotMarked': 'No attendance marks this month',
      'groupDetailsNeedMoment': 'Some class details need another moment.',
      'descriptionRequired': 'Please add a short description.',
      'requestCouldNotSend':
          'This request could not be sent from your account. Please contact your coordinator.',
      'active': 'Active',
      'course': 'Course',
      'month': 'Month',
      'studyMonthValue': 'Month {month}',
      'studyMonthRange': 'Enter a month from 1 to 600.',
      'level': 'Level',
      'mainTeacher': 'Main teacher',
      'branch': 'Branch',
      'currentBranch': 'Current branch',
      'destinationBranch': 'Destination branch',
      'moveGroupBranch': 'Move group to another branch',
      'moveStudentBranch': 'Move student to another branch',
      'transferReason': 'Reason for the move',
      'transferReasonHint': 'Add a short operational reason',
      'transferImpact': 'What changes',
      'groupTransferImpact':
          'Active students move with this group. The teaching team, room and future schedule are cleared so the destination branch can set them up safely.',
      'studentTransferImpact':
          'The student moves to the destination branch and leaves their current group. Their account and learning history remain intact.',
      'confirmTransferImpact': 'I reviewed and accept these changes',
      'transferAuditNotice':
          'This move is permanently recorded with its operator and reason.',
      'confirmBranchTransfer': 'Confirm branch move',
      'movingBranch': 'Moving…',
      'transferComplete': 'The branch move is complete.',
      'transferCouldNotComplete':
          'The branch move could not be completed. Check the details and try again.',
      'branchesLoadFailed': 'The branch list needs another moment.',
      'noTransferBranches': 'There is no other active branch available.',
      'department': 'Department',
      'mainRoom': 'Main room',
      'lessonCycle': 'Lesson cycle',
      'lessonCycleShort': '{count} lessons',
      'cycleProgress': '{completed} of {total} lessons completed',
      'cycleOverallProgress': '{count} lessons completed in total',
      'cycleNextLesson': 'Next cycle lesson: {number}',
      'cycleLessonsRemainingOne': '{count} lesson until exam day',
      'cycleLessonsRemainingOther': '{count} lessons until exam day',
      'cycleExamDue': 'The next completed lesson is the exam lesson',
      'cycleExamDueBody':
          'The exam is part of this group’s configured lesson cycle. Review the upcoming lesson and prepare the assessment.',
      'cycleCompletionIncomplete': 'A little schedule care is needed',
      'cycleCompletionIncompleteBody':
          '{count} past scheduled lesson(s) still need a completion status. Progress only counts confirmed completed lessons.',
      'cycleIncompleteOne':
          '{count} past lesson still needs a completion status. Progress only counts confirmed completed lessons.',
      'cycleIncompleteOther':
          '{count} past lessons still need a completion status. Progress only counts confirmed completed lessons.',
      'cycleLevelManual':
          'Level changes stay reviewed by the education team after results are available.',
      'cycleUnavailable': 'Cycle progress needs another moment',
      'cycleUnavailableBody':
          'The group remains available. Pull to refresh and check progress again.',
      'groupSummary': 'Group summary',
      'studentList': 'Student list',
      'history': 'History',
      'exams': 'Exams',
      'viewProfile': 'View profile',
      'call': 'Call',
      'message': 'Message',
      'requestAction': 'Request action',
      'requestMove': 'Request move',
      'requestHelp': 'Request help',
      'requestKick': 'Request removal',
      'requestReason': 'Explain the situation clearly',
      'sendRequest': 'Send request',
      'requestSent': 'Your request was sent to the responsible team.',
      'contactGuardian': 'Guardian',
      'phone': 'Phone',
      'dateOfBirth': 'Date of birth',
      'joined': 'Joined',
      'notes': 'Learning notes',
      'studentNotesUnavailable':
          'No learning notes have been shared for this student yet.',
      'studentOverview': 'Student overview',
      'academicLevel': 'Academic level',
      'email': 'Email',
      'location': 'Location',
      'previousSchool': 'Previous school',
      'attendanceSummary': 'Attendance summary',
      'recentResults': 'Recent results',
      'familyContacts': 'Family contacts',
      'assignmentsSummary': 'Assignments summary',
      'assigned': 'Assigned',
      'open': 'Open',
      'noFamilyContacts': 'No family contacts have been added yet.',
      'attendanceHistory': 'Attendance history',
      'lessonHistory': 'Lesson history',
      'previousMonth': 'Previous month',
      'nextMonth': 'Next month',
      'present': 'Present',
      'absent': 'Absent',
      'late': 'Late',
      'excused': 'Excused',
      'smartCard': 'Smart card',
      'warningCard': 'Warning card',
      'noCard': 'No card',
      'feedbackCard': 'Lesson card',
      'skillBreakdown': 'Skill breakdown',
      'overallScore': 'Overall score',
      'startAttendance': 'Start today’s attendance',
      'saveAttendance': 'Save attendance',
      'attendanceSaved': 'Attendance was saved successfully.',
      'attendanceSaveFailed':
          'Attendance could not be saved. Please review and try again.',
      'attendanceStartsAt': 'Attendance opens at {time}',
      'attendanceOpensIn': 'Attendance opens in {time}',
      'unmarked': 'Not marked',
      'studentsStillUnmarked': '{count} students still need a status.',
      'unsavedAttendanceTitle': 'Leave without saving?',
      'unsavedAttendanceBody':
          'Your attendance changes have not been saved yet.',
      'continueEditing': 'Keep editing',
      'discardChanges': 'Discard changes',
      'showingPreviousData':
          'Could not refresh. The previous attendance data is still shown.',
      'scheduled': 'Scheduled',
      'registerIncomplete': 'Incomplete register',
      'registerComplete': 'Complete register',
      'fullMonthView': 'Full month',
      'tapDayToFilter': 'Tap a lesson day to focus on it',
      'showAll': 'Show all',
      'markedLessons': 'Marked',
      'absences': 'Absences',
      'attendanceViewOnly': 'Attendance is view-only for this account',
      'noLessonsThisPeriod': 'A quiet part of the calendar',
      'noLessonsThisPeriodBody':
          'There are no scheduled lessons in this selection.',
      'attendanceNeedMoment': 'Attendance needs another moment',
      'examsNeedMoment': 'Exam history needs another moment',
      'noExamsYet': 'The next milestone starts here',
      'noExamsYetBody': 'Exam records will appear here when they are ready.',
      'examHistoryHint':
          'Open an exam to review published scores for the whole group.',
      'points': 'Points',
      'published': 'Published',
      'resultsPending': 'Results pending',
      'resultsViewLimited':
          'Detailed results are available to authorized teaching staff.',
      'resultsNeedMoment': 'The results need another moment. Please try again.',
      'allPresent': 'All present',
      'lesson': 'Lesson',
      'examDay': 'Exam day',
      'autoExamNote': 'Lesson 12 is automatically marked as the level exam.',
      'examHistory': 'Exam history',
      'passed': 'Passed',
      'needsRetry': 'Needs retry',
      'listening': 'Listening',
      'reading': 'Reading',
      'writing': 'Writing',
      'speaking': 'Speaking',
      'updateProgress': 'Update month & level',
      'save': 'Save',
      'myTasks': 'My tasks',
      'assignedToMe': 'Assigned to me',
      'createdByMe': 'Created by me',
      'board': 'Board',
      'tasksNeedMoment': 'Your tasks need another moment',
      'tasksShowingPrevious':
          'Could not refresh. Your previous task list is still shown.',
      'taskMoveFailed': 'The task could not be moved. Please try again.',
      'taskCreateFailed': 'The task could not be created. Please try again.',
      'taskTitleRequired': 'Please add a task title.',
      'noDueDate': 'No due date',
      'list': 'List',
      'toDo': 'To do',
      'inProgress': 'In progress',
      'blocked': 'Blocked',
      'done': 'Done',
      'cancelled': 'Cancelled',
      'taskViewOnly': 'Only the assignee can change this task.',
      'highPriority': 'High priority',
      'dueToday': 'Due today',
      'addTask': 'New task',
      'taskTitle': 'Task title',
      'description': 'Description',
      'dueDate': 'Due date',
      'createTask': 'Create task',
      'taskCreated': 'Task created.',
      'inbox': 'Inbox',
      'archived': 'Archived',
      'searchMessages': 'Search conversations',
      'newConversation': 'New conversation',
      'staff': 'Staff',
      'sendMessage': 'Message',
      'typeMessage': 'Message…',
      'online': 'Online',
      'recentlyActive': 'Recently active',
      'voiceMessage': 'Voice message',
      'holdToRecordVoice': 'Hold to record a voice message',
      'microphonePermissionNeeded':
          'Allow microphone access to record a voice message.',
      'voiceRecordingFailed':
          'The voice message could not be recorded. Please try again.',
      'voiceMessageTooShort': 'Hold a little longer to record your message.',
      'archiveConversation': 'Archive conversation',
      'unarchiveConversation': 'Move conversation to inbox',
      'conversationArchived': 'Conversation archived.',
      'movedToInbox': 'Conversation moved to inbox.',
      'resourceAudience': 'Who can see this after approval?',
      'ownStudentsAudience': 'My students',
      'globalAudience': 'Everyone',
      'audienceLocationUnavailable':
          'There is no approved location for that audience yet.',
      'allowDownloads': 'Allow downloads',
      'allowDownloadsBody': 'Approved viewers can save a copy.',
      'viewOnlyBody': 'Approved viewers can open it only inside Starforge.',
      'unsupportedAttachmentFormat':
          'Please choose JPG, PNG or WEBP for images, MP4 for video, or MP3 for audio.',
      'recording': 'Recording… release to send',
      'mediaSent': 'Media ready to send.',
      'unread': 'unread',
      'conversation': 'Conversation',
      'openConversation': 'Open conversation',
      'conversationUnavailable':
          'This conversation is not available right now. Please try again.',
      'noContacts': 'No one here yet',
      'noContactsBody': 'People you are allowed to message will appear here.',
      'noConversations': 'A quiet inbox',
      'noConversationsBody':
          'Start a conversation with one of your students or colleagues.',
      'noMessages': 'A fresh conversation',
      'noMessagesBody': 'Say hello when you are ready.',
      'messagesLoadFailed': 'Your conversations need another moment',
      'messagesLoadFailedBody': 'Please check your connection and try again.',
      'messageSendFailed':
          'That message was not sent. Your text is still here.',
      'messageAttachmentFailed':
          'That attachment could not be sent. Please try again.',
      'readOnlyConversation': 'You can read this conversation.',
      'attachment': 'Attachment',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'audio': 'Audio',
      'file': 'File',
      'librarySubtitle': 'Books, audio and video lessons in one calm space.',
      'awaitingTeacherApproval': 'Teacher review',
      'awaitingPublication': 'Final review',
      'approveResource': 'Approve resource',
      'resourceApproved': 'Resource approved for final review.',
      'resourceApprovalFailed': 'This resource could not be approved.',
      'downloadResource': 'Download',
      'searchLibrary': 'Search the library',
      'all': 'All',
      'books': 'Books',
      'playlists': 'Playlists',
      'podcasts': 'Podcasts',
      'videos': 'Videos',
      'recentlyAdded': 'Recently added',
      'popularPlaylists': 'Curated playlists',
      'upload': 'Upload',
      'uploadResource': 'Upload a resource',
      'resourceTitle': 'Resource title',
      'audience': 'Audience',
      'everyone': 'Everyone',
      'myStudents': 'My students only',
      'allowDownload': 'Allow download',
      'protectedContent':
          'View-only: downloading is unavailable and your identity is watermarked.',
      'protectedWatermark': 'Viewed by {identity}',
      'chooseFile': 'Choose file',
      'publish': 'Publish',
      'uploadReady': 'Resource prepared for publishing.',
      'resources': 'resources',
      'contentLocation': 'Library folder',
      'resourceReviewNote':
          'Your resource is checked before it becomes available. Its audience and download access follow the selected library’s policy.',
      'noUploadLocation':
          'There is no available library folder for this account yet.',
      'uploadSubmitted': 'Your resource was uploaded and is being prepared.',
      'uploadFailed': 'The resource could not be uploaded. Please try again.',
      'uploading': 'Uploading…',
      'resourceBeingPrepared':
          'This resource is still being prepared. Check again shortly.',
      'resourceUnavailable':
          'This resource is not available right now. Please try again later.',
      'rejected': 'Needs attention',
      'draft': 'Draft',
      'statusOpen': 'Open',
      'statusClosed': 'Closed',
      'statusIssued': 'Issued',
      'statusPartiallyPaid': 'Partially paid',
      'statusPaid': 'Paid',
      'statusVoid': 'Void',
      'statusOverdue': 'Overdue',
      'statusPending': 'Processing',
      'statusClean': 'Ready',
      'starforgeLibrary': 'Starforge Library',
      'libraryLoadFailed': 'The library needs another moment',
      'libraryLoadFailedBody': 'Please check your connection and try again.',
      'openResource': 'Open resource',
      'availablePrinters': 'Available printers',
      'printerSubtitle': 'Send, customize, or schedule secure print jobs.',
      'available': 'Available',
      'busy': 'Busy',
      'paper': 'Paper',
      'copies': 'Copies',
      'color': 'Color',
      'blackWhite': 'Black & white',
      'doubleSided': 'Double-sided',
      'schedulePrint': 'Schedule print',
      'printNow': 'Print now',
      'selectMaterial': 'Select material',
      'fromLibrary': 'From library',
      'fromDevice': 'From device',
      'scheduledJobs': 'Scheduled jobs',
      'printQueued': 'Your secure print job was queued.',
      'jobScheduled': 'Print job scheduled.',
      'printLibrarySourceNote':
          'Prepared assignments, reports, receipts, and transcripts can be printed.',
      'printRequestUnavailable':
          'This document is not ready for secure printing yet.',
      'printFileUnsupported':
          'Choose a PDF, JPEG, PNG, or WebP file from your device.',
      'printLibraryTitle': 'Choose from the library',
      'noPrintableMaterials': 'No printable materials yet',
      'noPrintableMaterialsBody':
          'Download-enabled PDF and image resources will appear here.',
      'decreaseCopies': 'Decrease copies',
      'increaseCopies': 'Increase copies',
      'printScheduleFuture': 'Choose a time in the future.',
      'printSubmitFailed':
          'The print job could not be submitted. Please check the material and try again.',
      'submittingPrint': 'Submitting…',
      'printerOffline': 'Offline',
      'noPrinters': 'No printers are available for your branch right now.',
      'readyToConfigure': 'Ready to configure',
      'printerReady': 'Ready for print jobs',
      'noPrintJobs': 'No print jobs yet',
      'noPrintJobsBody': 'Your print history will appear here.',
      'queued': 'Queued',
      'picked': 'Accepted',
      'printing': 'Printing',
      'failed': 'Needs attention',
      'needsReview': 'Review needed',
      'assignment': 'Assignment',
      'transcript': 'Transcript',
      'report': 'Report',
      'receipt': 'Receipt',
      'document': 'Document',
      'pages': 'pages',
      'workingSince': 'Working since',
      'salaryHistory': 'Salary history',
      'salaryCurrent': 'Current salary',
      'salaryPrivate':
          'Private employment information visible only to you and authorized finance staff.',
      'noPayslips': 'No payslips yet',
      'noPayslipsBody':
          'Your verified payslips will appear here when available.',
      'payslipPaid': 'Paid',
      'payslipPending': 'Pending',
      'employmentDataUnavailable': 'Employment details are not available',
      'employmentDataUnavailableBody':
          'Please contact administration if you need a verified employment record.',
      'contract': 'Contract',
      'contractUnavailable': 'Contract is not available',
      'contractUnavailableBody':
          'A verified contract will appear here when administration publishes it.',
      'employment': 'Employment',
      'stats': 'Work stats',
      'years': 'years',
      'rating': 'Rating',
      'rules': 'Education center rules',
      'rulesRequired': 'Required standard',
      'ruleVersion': 'Policy version',
      'acknowledge': 'Acknowledge',
      'acknowledged': 'Acknowledged',
      'ruleAcknowledged': 'You acknowledged this rule.',
      'rulesLoadFailed': 'Rules could not be loaded. Please try again.',
      'rulesSubtitle': 'Teaching standards, staff conduct, and safety.',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'language': 'Language',
      'theme': 'Theme',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'accentColor': 'Accent color',
      'defaultShift': 'Default shift',
      'morningShift': 'Morning · 08:00–14:00',
      'afternoonShift': 'Afternoon · 14:00–20:00',
      'fullDayShift': 'Full day · 09:00–18:00',
      'notifications': 'Notifications',
      'markAllRead': 'Mark all as read',
      'notificationsEmpty': 'You’re all caught up',
      'notificationsEmptyBody':
          'Important updates and reminders will appear here.',
      'notificationsLoadFailed':
          'Notifications could not be loaded. Please try again.',
      'notificationsLoadFailedBody':
          'Your updates are still safe. Check your connection and refresh when you are ready.',
      'notificationsStale': 'Showing your last loaded notifications.',
      'lastUpdatedAt': 'Last updated {time}',
      'notificationReadSaveFailed':
          'The update opened, but its read status could not be saved.',
      'close': 'Close',
      'lessonReminders': 'Lesson reminders',
      'privacyRoleVisibility': 'Role-based visibility',
      'privacyRoleVisibilityBody':
          'You only see information needed for your assigned work.',
      'privacyProtectedContent': 'Protected learning content',
      'privacyProtectedContentBody':
          'View-only materials stay inside the app, carry your identity watermark, and use device capture controls where supported.',
      'privacyAccountability': 'Accountability',
      'privacyAccountabilityBody':
          'Sensitive actions are protected and recorded.',
      'accentOption': '{color} accent color',
      'accentindigo': 'Saroy',
      'accentocean': 'Marvarid',
      'accentcoral': 'Samarqand',
      'accentforest': 'Daryo',
      'accentazure': 'Osmon',
      'accentamber': 'Uchqun',
      'accentheritage': 'Meros',
      'security': 'Security',
      'changePassword': 'Change password',
      'editName': 'Edit name',
      'editProfile': 'Edit profile',
      'firstName': 'First name',
      'middleName': 'Middle name',
      'lastName': 'Last name',
      'openSettings': 'Open settings',
      'newName': 'Display name',
      'about': 'About Starforge Staff',
      'version': 'Version 1.0.0 (1)',
      'versionValue': 'Version {version}',
      'signOut': 'Sign out',
      'signOutConfirm': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'emptyTitle': 'Nothing here yet',
      'emptyBody': 'When something needs your attention, it will appear here.',
      'actionUnavailable':
          'This feature is not available for your account yet.',
      'workspace': 'Workspace',
      'studio': 'Studio',
      'frontDesk': 'Front desk',
      'leads': 'Leads',
      'finance': 'Finance',
      'overview': 'Overview',
      'todaysFocus': 'Today’s focus',
      'pending': 'Pending',
      'urgent': 'Urgent',
      'queue': 'Queue',
      'newItem': 'New item',
      'roleReady': 'Your role workspace is ready.',
      'openTasksCountOne': '{count} open task',
      'openTasksCountOther': '{count} open tasks',
      'unreadCountOne': '{count} unread conversation',
      'unreadCountOther': '{count} unread conversations',
      'studentsCountOne': '{count} student',
      'studentsCountOther': '{count} students',
      'groupsCountOne': '{count} assigned group',
      'groupsCountOther': '{count} assigned groups',
      'lessonsCountOne': '{count} lesson',
      'lessonsCountOther': '{count} lessons',
      'examsCountOne': '{count} exam',
      'examsCountOther': '{count} exams',
      'pointsCountOne': '{count} point',
      'pointsCountOther': '{count} points',
      'pagesCountOne': '{count} page',
      'pagesCountOther': '{count} pages',
      'copiesCountOne': '{count} copy',
      'copiesCountOther': '{count} copies',
      'attendancePercent': '{percent}% attendance',
    },
    'ru': {
      'appName': 'Starforge Staff',
      'welcomeBack': 'С возвращением',
      'loginSubtitle': 'Ваше спокойное рабочее пространство.',
      'loginEyebrow': 'РАБОЧЕЕ ПРОСТРАНСТВО',
      'loginPromise': 'Планируйте ясно. Обучайте уверенно.',
      'loginDetail':
          'Уроки, ученики, задачи и общение — всё продуманно организовано для вашего дня.',
      'username': 'Логин',
      'password': 'Пароль',
      'usernameRequired': 'Введите логин.',
      'passwordTooShort': 'Пароль должен содержать не менее 4 символов.',
      'passwordRequired': 'Введите пароль.',
      'showPassword': 'Показать пароль',
      'hidePassword': 'Скрыть пароль',
      'signIn': 'Войти',
      'forgotPassword': 'Забыли пароль?',
      'forgotMessage':
          'Обратитесь к администрации. Они безопасно сбросят ваш пароль.',
      'privacyPolicy': 'Политика конфиденциальности',
      'viewFullPolicy': 'Открыть полную политику',
      'policyOpenFailed':
          'Не удалось безопасно открыть политику. Попробуйте снова.',
      'terms': 'Конфиденциальность и условия для сотрудников',
      'termsBody':
          'Starforge защищает данные сотрудников и учеников. Доступ зависит от роли, действия могут регистрироваться, а учебные записи разрешено использовать только для утверждённой работы центра.',
      'role': 'Роль сотрудника',
      'teacher': 'Преподаватель',
      'assistant': 'Ассистент',
      'media': 'Медиа',
      'reception': 'Ресепшен',
      'sales': 'Отдел продаж',
      'printer': 'Печать',
      'cashier': 'Кассир',
      'staffMember': 'Сотрудник',
      'invalidLogin': 'Неверный логин или пароль.',
      'restrictedLogin':
          'Руководители используют приложение Starforge Management.',
      'loginUnavailable':
          'Сейчас не удалось войти. Проверьте подключение и повторите попытку.',
      'loginRateLimited':
          'Было несколько попыток. Подождите немного и попробуйте снова.',
      'roleAuto': 'Пространство настроится под вашу учётную запись',
      'secureWorkspace': 'Закрытое пространство сотрудников',
      'passwordRequiredTitle': 'Создайте новый пароль',
      'passwordRequiredBody':
          'Для вашей защиты выберите новый пароль перед продолжением.',
      'currentPassword': 'Текущий пароль',
      'newPassword': 'Новый пароль',
      'confirmPassword': 'Повторите новый пароль',
      'updatePassword': 'Обновить пароль',
      'passwordRules': 'Используйте не менее 10 символов.',
      'passwordMismatch': 'Новые пароли не совпадают.',
      'passwordUpdateFailed':
          'Не удалось обновить пароль. Проверьте текущий пароль и попробуйте снова.',
      'passwordUpdated': 'Пароль обновлён.',
      'changesSaved': 'Изменения сохранены.',
      'changesCouldNotSave':
          'Не удалось сохранить изменения. Попробуйте снова.',
      'warmLogin': 'Рады вас видеть. Всё готово для продуктивного дня.',
      'home': 'Главная',
      'groups': 'Группы',
      'tasks': 'Задачи',
      'messages': 'Сообщения',
      'profile': 'Профиль',
      'workHub': 'Работа',
      'workHubTitle': 'Полное рабочее пространство',
      'workHubSubtitle':
          'Ученики, материалы, опросы, запросы, награды, отчёты и профиль.',
      'workNowTitle': 'Требует внимания',
      'workResourcesTitle': 'Инструменты и записи',
      'workAccountTitle': 'Работа и учётная запись',
      'assignedStudents': 'Мои ученики',
      'assignedStudentsSubtitle': 'Только ученики из ваших групп.',
      'formsSurveys': 'Формы и опросы',
      'formsSurveysSubtitle': 'Отвечайте на доступные вам опросы.',
      'requests': 'Запросы',
      'requestsSubtitle': 'Создавайте и отслеживайте рабочие запросы.',
      'achievements': 'Достижения',
      'achievementsSubtitle': 'Награждайте учеников из своих групп.',
      'reports': 'Отчёты',
      'reportsSubtitle': 'Готовьте и отправляйте учебные отчёты.',
      'goodMorning': 'Доброе утро',
      'goodAfternoon': 'Добрый день',
      'goodEvening': 'Добрый вечер',
      'motivation1': 'Маленький ежедневный прогресс ведёт к мастерству.',
      'motivation2': 'Ваше внимание может изменить весь день ученика.',
      'motivation3': 'Объясняйте ясно. Ведите с добротой.',
      'motivation4': 'Сегодня можно снова сделать обучение доступным.',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'nextLesson': 'Следующий урок',
      'room': 'Кабинет',
      'students': 'Ученики',
      'totalStudents': 'Всего учеников',
      'attendance': 'Посещаемость',
      'startsIn': 'Начало через {time}',
      'durationHoursMinutes': '{hours} ч {minutes} мин',
      'durationMinutes': '{minutes} мин',
      'quickActions': 'Быстрые действия',
      'takeAttendance': 'Отметить посещаемость',
      'openTasks': 'Открыть задачи',
      'library': 'Библиотека',
      'printCenter': 'Центр печати',
      'important': 'Важно',
      'meeting': 'Встреча',
      'meetingsTitle': 'Встречи',
      'meetingsSubtitle':
          'Предстоящие встречи в доступной вам рабочей области.',
      'meetingsEmpty': 'Нет предстоящих встреч',
      'meetingsEmptyBody': 'Новые приглашения появятся здесь после назначения.',
      'meetingsLoadFailed': 'Не удалось загрузить встречи',
      'meetingPending': 'Ожидает вашего ответа',
      'meetingAccepted': 'Принято',
      'meetingDeclined': 'Отклонено',
      'acceptMeeting': 'Принять',
      'declineMeeting': 'Отклонить',
      'meetingResponseSaved': 'Ваш ответ на приглашение сохранён.',
      'meetingResponseFailed': 'Не удалось сохранить ответ на приглашение.',
      'schedule': 'Расписание на сегодня',
      'upcomingSchedule': 'Ближайшее расписание',
      'upcoming': 'Впереди',
      'openAttendance': 'Открыть посещаемость',
      'noUpcomingLessons': 'Ближайшее расписание свободно',
      'noUpcomingLessonsBody':
          'Новые уроки появятся здесь сразу после назначения.',
      'dashboardNeedsMoment':
          'Некоторым обновлениям нужно ещё немного времени.',
      'suggestion': 'Совет',
      'academicDepartment': 'Учебный отдел',
      'seeAll': 'Смотреть все',
      'aiInsight': 'Совет ИИ',
      'aiUnavailable': 'ИИ взял короткую паузу. Попробуйте позже.',
      'aiNoRecommendations':
          'ИИ доступен. Сейчас для вас нет проверенной рекомендации.',
      'aiDegraded':
          'ИИ работает немного медленнее обычного, поэтому рекомендации временно приостановлены.',
      'aiStatusUnavailable':
          'Сейчас не удалось проверить ИИ. Остальные инструменты доступны.',
      'aiStatusChecking': 'Проверяем доступность ИИ…',
      'featureAvailable': 'Доступен',
      'featureDegraded': 'Ограничен',
      'featureUnavailable': 'На паузе',
      'featureStatusUnknown': 'Статус уточняется',
      'featureUnavailablePolite':
          'Этот раздел взял короткую паузу. Пожалуйста, вернитесь немного позже.',
      'weeklyPulse': 'Итоги недели',
      'lessons': 'Уроки',
      'completed': 'Завершено',
      'onTime': 'Вовремя',
      'reviewsDue': 'Нужно проверить',
      'announcements': 'Объявления',
      'noAnnouncements': 'Сейчас объявлений нет.',
      'yourGroups': 'Ваши группы',
      'groupsSubtitle': 'Показаны только назначенные вам группы.',
      'searchGroups': 'Поиск групп',
      'assignedGroups': 'Назначенные группы',
      'groupPortfolio': 'Учебная группа',
      'capacity': 'Вместимость',
      'refresh': 'Обновить',
      'tryAgain': 'Попробовать снова',
      'search': 'Поиск',
      'clear': 'Очистить',
      'noItems': 'Здесь пока ничего нет',
      'noAssignedGroups': 'Здесь появится всё важное',
      'noAssignedGroupsBody':
          'Назначенные вам группы появятся здесь, как только будут готовы.',
      'groupsLoadFailed': 'Группам нужна ещё минута',
      'groupsLoadFailedBody': 'Проверьте подключение и попробуйте ещё раз.',
      'studentListPreparing': 'Готовим актуальный список класса',
      'noStudentsYet': 'Новый список класса',
      'noStudentsYetBody':
          'Ученики этой группы появятся здесь после зачисления.',
      'attendanceNotMarked': 'В этом месяце пока нет отметок',
      'groupDetailsNeedMoment':
          'Части данных группы нужно ещё немного времени.',
      'descriptionRequired': 'Добавьте короткое описание.',
      'requestCouldNotSend':
          'Не удалось отправить запрос из вашей учётной записи. Обратитесь к координатору.',
      'active': 'Активна',
      'course': 'Курс',
      'month': 'Месяц',
      'studyMonthValue': 'Месяц {month}',
      'studyMonthRange': 'Введите месяц от 1 до 600.',
      'level': 'Уровень',
      'mainTeacher': 'Основной преподаватель',
      'branch': 'Филиал',
      'currentBranch': 'Текущий филиал',
      'destinationBranch': 'Новый филиал',
      'moveGroupBranch': 'Перевести группу в другой филиал',
      'moveStudentBranch': 'Перевести ученика в другой филиал',
      'transferReason': 'Причина перевода',
      'transferReasonHint': 'Кратко укажите рабочую причину',
      'transferImpact': 'Что изменится',
      'groupTransferImpact':
          'Активные ученики переходят вместе с группой. Преподаватели, кабинет и будущие занятия очищаются для безопасной настройки в новом филиале.',
      'studentTransferImpact':
          'Ученик переходит в новый филиал и выходит из текущей группы. Учётная запись и история обучения сохраняются.',
      'confirmTransferImpact': 'Я проверил и принимаю эти изменения',
      'transferAuditNotice':
          'Перевод навсегда сохраняется с исполнителем и причиной.',
      'confirmBranchTransfer': 'Подтвердить перевод',
      'movingBranch': 'Переводим…',
      'transferComplete': 'Перевод в филиал завершён.',
      'transferCouldNotComplete':
          'Не удалось завершить перевод. Проверьте данные и повторите попытку.',
      'branchesLoadFailed': 'Списку филиалов нужно ещё немного времени.',
      'noTransferBranches': 'Другого активного филиала сейчас нет.',
      'department': 'Отдел',
      'mainRoom': 'Основной кабинет',
      'lessonCycle': 'Цикл занятий',
      'lessonCycleShort': '{count} занятий',
      'cycleProgress': 'Завершено {completed} из {total} занятий',
      'cycleOverallProgress': 'Всего завершено занятий: {count}',
      'cycleNextLesson': 'Следующее занятие цикла: {number}',
      'cycleLessonsRemainingOne': '{count} занятие до экзамена',
      'cycleLessonsRemainingFew': '{count} занятия до экзамена',
      'cycleLessonsRemainingMany': '{count} занятий до экзамена',
      'cycleExamDue': 'Следующее завершённое занятие — экзамен',
      'cycleExamDueBody':
          'Экзамен входит в настроенный цикл группы. Проверьте ближайшее занятие и подготовьте оценивание.',
      'cycleCompletionIncomplete': 'Расписанию нужно немного внимания',
      'cycleCompletionIncompleteBody':
          'Для прошлых запланированных занятий без статуса: {count}. В прогресс входят только подтверждённые завершённые занятия.',
      'cycleIncompleteOne':
          'Для {count} прошлого занятия нужен статус завершения. В прогресс входят только подтверждённые занятия.',
      'cycleIncompleteFew':
          'Для {count} прошлых занятий нужен статус завершения. В прогресс входят только подтверждённые занятия.',
      'cycleIncompleteMany':
          'Для {count} прошлых занятий нужен статус завершения. В прогресс входят только подтверждённые занятия.',
      'cycleLevelManual':
          'Изменение уровня подтверждает учебная команда после появления результатов.',
      'cycleUnavailable': 'Прогресс цикла пока не загрузился',
      'cycleUnavailableBody':
          'Группа остаётся доступной. Потяните экран для обновления и проверьте снова.',
      'groupSummary': 'Сводка группы',
      'studentList': 'Список учеников',
      'history': 'История',
      'exams': 'Экзамены',
      'viewProfile': 'Открыть профиль',
      'call': 'Позвонить',
      'message': 'Написать',
      'requestAction': 'Отправить запрос',
      'requestMove': 'Запросить перевод',
      'requestHelp': 'Запросить помощь',
      'requestKick': 'Запросить исключение',
      'requestReason': 'Подробно опишите ситуацию',
      'sendRequest': 'Отправить запрос',
      'requestSent': 'Запрос отправлен ответственной команде.',
      'contactGuardian': 'Опекун',
      'phone': 'Телефон',
      'dateOfBirth': 'Дата рождения',
      'joined': 'Дата начала',
      'notes': 'Заметки об обучении',
      'studentNotesUnavailable':
          'Для этого ученика пока нет доступных учебных заметок.',
      'studentOverview': 'Обзор ученика',
      'academicLevel': 'Академический уровень',
      'email': 'Эл. почта',
      'location': 'Местоположение',
      'previousSchool': 'Предыдущая школа',
      'attendanceSummary': 'Сводка посещаемости',
      'recentResults': 'Последние результаты',
      'familyContacts': 'Контакты семьи',
      'assignmentsSummary': 'Сводка заданий',
      'assigned': 'Назначено',
      'open': 'Открыто',
      'noFamilyContacts': 'Контакты семьи пока не добавлены.',
      'attendanceHistory': 'История посещаемости',
      'lessonHistory': 'История уроков',
      'previousMonth': 'Предыдущий месяц',
      'nextMonth': 'Следующий месяц',
      'present': 'Присутствовал',
      'absent': 'Отсутствовал',
      'late': 'Опоздал',
      'excused': 'Уважительная причина',
      'smartCard': 'Smart-карта',
      'warningCard': 'Предупреждение',
      'noCard': 'Без карты',
      'feedbackCard': 'Карта урока',
      'skillBreakdown': 'Баллы по навыкам',
      'overallScore': 'Общий балл',
      'startAttendance': 'Начать посещаемость сегодня',
      'saveAttendance': 'Сохранить',
      'attendanceSaved': 'Посещаемость сохранена.',
      'attendanceSaveFailed':
          'Не удалось сохранить посещаемость. Проверьте данные и повторите попытку.',
      'attendanceStartsAt': 'Посещаемость откроется в {time}',
      'attendanceOpensIn': 'Посещаемость откроется через {time}',
      'unmarked': 'Не отмечено',
      'studentsStillUnmarked': 'Ещё не отмечено учеников: {count}.',
      'unsavedAttendanceTitle': 'Выйти без сохранения?',
      'unsavedAttendanceBody': 'Изменения посещаемости ещё не сохранены.',
      'continueEditing': 'Продолжить',
      'discardChanges': 'Отменить изменения',
      'showingPreviousData':
          'Обновить не удалось. Показаны предыдущие данные посещаемости.',
      'scheduled': 'Запланировано',
      'registerIncomplete': 'Журнал не заполнен',
      'registerComplete': 'Журнал заполнен',
      'fullMonthView': 'Весь месяц',
      'tapDayToFilter': 'Нажмите на день урока, чтобы открыть его',
      'showAll': 'Показать всё',
      'markedLessons': 'Отмечено',
      'absences': 'Пропуски',
      'attendanceViewOnly': 'Для этой учётной записи доступен только просмотр',
      'noLessonsThisPeriod': 'Спокойная часть календаря',
      'noLessonsThisPeriodBody':
          'В выбранном периоде нет запланированных уроков.',
      'attendanceNeedMoment': 'Посещаемости нужно ещё немного времени',
      'examsNeedMoment': 'Истории экзаменов нужно ещё немного времени',
      'noExamsYet': 'Следующий этап начинается здесь',
      'noExamsYetBody': 'Экзамены появятся здесь, когда будут готовы.',
      'examHistoryHint':
          'Откройте экзамен, чтобы посмотреть опубликованные оценки всей группы.',
      'points': 'Баллы',
      'published': 'Опубликовано',
      'resultsPending': 'Результаты ожидаются',
      'resultsViewLimited':
          'Подробные результаты доступны уполномоченным преподавателям.',
      'resultsNeedMoment':
          'Результатам нужно ещё немного времени. Повторите попытку.',
      'allPresent': 'Все присутствуют',
      'lesson': 'Урок',
      'examDay': 'Экзамен',
      'autoExamNote': 'Урок 12 автоматически отмечен как экзамен.',
      'examHistory': 'История экзаменов',
      'passed': 'Сдал',
      'needsRetry': 'Пересдача',
      'listening': 'Аудирование',
      'reading': 'Чтение',
      'writing': 'Письмо',
      'speaking': 'Речь',
      'updateProgress': 'Изменить месяц и уровень',
      'save': 'Сохранить',
      'myTasks': 'Мои задачи',
      'assignedToMe': 'Назначено мне',
      'createdByMe': 'Создано мной',
      'board': 'Доска',
      'tasksNeedMoment': 'Задачам нужно ещё немного времени',
      'tasksShowingPrevious':
          'Обновить не удалось. Показан предыдущий список задач.',
      'taskMoveFailed': 'Не удалось переместить задачу. Попробуйте снова.',
      'taskCreateFailed': 'Не удалось создать задачу. Попробуйте снова.',
      'taskTitleRequired': 'Добавьте название задачи.',
      'noDueDate': 'Без срока',
      'list': 'Список',
      'toDo': 'Нужно сделать',
      'inProgress': 'В работе',
      'blocked': 'Заблокировано',
      'done': 'Готово',
      'cancelled': 'Отменено',
      'taskViewOnly': 'Изменять эту задачу может только исполнитель.',
      'highPriority': 'Высокий приоритет',
      'dueToday': 'Сегодня',
      'addTask': 'Новая задача',
      'taskTitle': 'Название задачи',
      'description': 'Описание',
      'dueDate': 'Срок',
      'createTask': 'Создать задачу',
      'taskCreated': 'Задача создана.',
      'inbox': 'Входящие',
      'archived': 'Архив',
      'searchMessages': 'Поиск диалогов',
      'newConversation': 'Новый диалог',
      'staff': 'Сотрудники',
      'sendMessage': 'Сообщение',
      'typeMessage': 'Сообщение…',
      'online': 'В сети',
      'recentlyActive': 'Недавно был(а) активен(на)',
      'voiceMessage': 'Голосовое сообщение',
      'holdToRecordVoice': 'Удерживайте, чтобы записать голосовое сообщение',
      'microphonePermissionNeeded':
          'Разрешите доступ к микрофону для записи голосового сообщения.',
      'voiceRecordingFailed':
          'Не удалось записать голосовое сообщение. Попробуйте снова.',
      'voiceMessageTooShort': 'Удерживайте дольше, чтобы записать сообщение.',
      'archiveConversation': 'Архивировать диалог',
      'unarchiveConversation': 'Вернуть диалог во входящие',
      'conversationArchived': 'Диалог перемещён в архив.',
      'movedToInbox': 'Диалог перемещён во входящие.',
      'resourceAudience': 'Кто увидит материал после одобрения?',
      'ownStudentsAudience': 'Мои ученики',
      'globalAudience': 'Все пользователи',
      'audienceLocationUnavailable':
          'Для этой аудитории пока нет разрешённого раздела.',
      'allowDownloads': 'Разрешить скачивание',
      'allowDownloadsBody': 'После одобрения файл можно будет сохранить.',
      'viewOnlyBody':
          'После одобрения материал откроется только внутри Starforge.',
      'unsupportedAttachmentFormat':
          'Выберите JPG, PNG или WEBP для фото, MP4 для видео либо MP3 для аудио.',
      'recording': 'Запись… отпустите для отправки',
      'mediaSent': 'Медиа готово к отправке.',
      'unread': 'непрочитанных',
      'conversation': 'Диалог',
      'openConversation': 'Открыть диалог',
      'conversationUnavailable':
          'Сейчас этот диалог недоступен. Попробуйте ещё раз.',
      'noContacts': 'Здесь пока никого нет',
      'noContactsBody':
          'Здесь появятся ученики и коллеги, которым вы можете писать.',
      'noConversations': 'Здесь пока тихо',
      'noConversationsBody': 'Начните диалог с учеником или коллегой.',
      'noMessages': 'Новый диалог',
      'noMessagesBody': 'Напишите первое сообщение, когда будете готовы.',
      'messagesLoadFailed': 'Диалогам нужна ещё секунда',
      'messagesLoadFailedBody': 'Проверьте подключение и попробуйте ещё раз.',
      'messageSendFailed': 'Сообщение не отправлено. Ваш текст сохранён здесь.',
      'messageAttachmentFailed':
          'Не удалось отправить вложение. Попробуйте ещё раз.',
      'readOnlyConversation': 'Вы можете читать этот диалог.',
      'attachment': 'Вложение',
      'camera': 'Камера',
      'gallery': 'Галерея',
      'audio': 'Аудио',
      'file': 'Файл',
      'librarySubtitle': 'Книги, аудио и видеоуроки в одном удобном месте.',
      'awaitingTeacherApproval': 'Проверка учителя',
      'awaitingPublication': 'Финальная проверка',
      'approveResource': 'Одобрить материал',
      'resourceApproved': 'Материал отправлен на финальную проверку.',
      'resourceApprovalFailed': 'Не удалось одобрить этот материал.',
      'downloadResource': 'Скачать',
      'searchLibrary': 'Поиск в библиотеке',
      'all': 'Все',
      'books': 'Книги',
      'playlists': 'Плейлисты',
      'podcasts': 'Подкасты',
      'videos': 'Видео',
      'recentlyAdded': 'Недавно добавлено',
      'popularPlaylists': 'Подборки',
      'upload': 'Загрузить',
      'uploadResource': 'Загрузить материал',
      'resourceTitle': 'Название материала',
      'audience': 'Аудитория',
      'everyone': 'Все',
      'myStudents': 'Только мои ученики',
      'allowDownload': 'Разрешить скачивание',
      'protectedContent':
          'Только просмотр: скачивание недоступно, на материале видна ваша отметка.',
      'protectedWatermark': 'Просматривает: {identity}',
      'chooseFile': 'Выбрать файл',
      'publish': 'Опубликовать',
      'uploadReady': 'Материал подготовлен к публикации.',
      'resources': 'материалов',
      'contentLocation': 'Папка библиотеки',
      'resourceReviewNote':
          'Материал проходит проверку перед публикацией. Аудитория и скачивание определяются правилами выбранной библиотеки.',
      'noUploadLocation':
          'Для этого аккаунта пока нет доступной папки библиотеки.',
      'uploadSubmitted': 'Материал загружен и готовится к публикации.',
      'uploadFailed': 'Не удалось загрузить материал. Попробуйте ещё раз.',
      'uploading': 'Загрузка…',
      'resourceBeingPrepared':
          'Материал ещё готовится. Загляните сюда чуть позже.',
      'resourceUnavailable': 'Сейчас материал недоступен. Попробуйте позже.',
      'rejected': 'Нужно исправить',
      'draft': 'Черновик',
      'statusOpen': 'Открыта',
      'statusClosed': 'Закрыта',
      'statusIssued': 'Выставлен',
      'statusPartiallyPaid': 'Частично оплачен',
      'statusPaid': 'Оплачен',
      'statusVoid': 'Аннулирован',
      'statusOverdue': 'Просрочен',
      'statusPending': 'Обрабатывается',
      'statusClean': 'Готово',
      'starforgeLibrary': 'Библиотека Starforge',
      'libraryLoadFailed': 'Библиотеке нужна ещё секунда',
      'libraryLoadFailedBody': 'Проверьте подключение и попробуйте ещё раз.',
      'openResource': 'Открыть материал',
      'availablePrinters': 'Доступные принтеры',
      'printerSubtitle': 'Настройте или запланируйте безопасную печать.',
      'available': 'Доступен',
      'busy': 'Занят',
      'paper': 'Бумага',
      'copies': 'Копии',
      'color': 'Цветная',
      'blackWhite': 'Чёрно-белая',
      'doubleSided': 'Двусторонняя',
      'schedulePrint': 'Запланировать',
      'printNow': 'Печатать сейчас',
      'selectMaterial': 'Выбрать материал',
      'fromLibrary': 'Из библиотеки',
      'fromDevice': 'С устройства',
      'scheduledJobs': 'Запланированная печать',
      'printQueued': 'Задание добавлено в очередь.',
      'jobScheduled': 'Печать запланирована.',
      'printLibrarySourceNote':
          'Можно печатать подготовленные задания, отчёты, чеки и ведомости.',
      'printRequestUnavailable':
          'Этот документ ещё не готов к защищённой печати.',
      'printFileUnsupported':
          'Выберите на устройстве файл PDF, JPEG, PNG или WebP.',
      'printLibraryTitle': 'Выбрать из библиотеки',
      'noPrintableMaterials': 'Нет материалов для печати',
      'noPrintableMaterialsBody':
          'Здесь появятся доступные для скачивания PDF и изображения.',
      'decreaseCopies': 'Уменьшить количество копий',
      'increaseCopies': 'Увеличить количество копий',
      'printScheduleFuture': 'Выберите время в будущем.',
      'printSubmitFailed':
          'Не удалось отправить задание. Проверьте материал и попробуйте ещё раз.',
      'submittingPrint': 'Отправка…',
      'printerOffline': 'Не в сети',
      'noPrinters': 'Сейчас в вашем филиале нет доступных принтеров.',
      'readyToConfigure': 'Можно настроить',
      'printerReady': 'Готов к печати',
      'noPrintJobs': 'Заданий на печать пока нет',
      'noPrintJobsBody': 'История печати появится здесь.',
      'queued': 'В очереди',
      'picked': 'Принято',
      'printing': 'Печатается',
      'failed': 'Нужно внимание',
      'needsReview': 'Нужна проверка',
      'assignment': 'Задание',
      'transcript': 'Ведомость',
      'report': 'Отчёт',
      'receipt': 'Чек',
      'document': 'Документ',
      'pages': 'стр.',
      'workingSince': 'Работает с',
      'salaryHistory': 'История зарплаты',
      'salaryCurrent': 'Текущая зарплата',
      'salaryPrivate':
          'Личная информация о работе видна только вам и уполномоченным сотрудникам финансового отдела.',
      'noPayslips': 'Расчётных листов пока нет',
      'noPayslipsBody':
          'Подтверждённые расчётные листы появятся здесь, когда будут доступны.',
      'payslipPaid': 'Оплачено',
      'payslipPending': 'Ожидается',
      'employmentDataUnavailable': 'Данные о работе недоступны',
      'employmentDataUnavailableBody':
          'Если вам нужна подтверждённая справка, обратитесь к администрации.',
      'contract': 'Контракт',
      'contractUnavailable': 'Контракт недоступен',
      'contractUnavailableBody':
          'Подтверждённый контракт появится здесь после публикации администрацией.',
      'employment': 'Трудовые данные',
      'stats': 'Статистика работы',
      'years': 'года',
      'rating': 'Рейтинг',
      'rules': 'Правила учебного центра',
      'rulesRequired': 'Обязательный стандарт',
      'ruleVersion': 'Версия политики',
      'acknowledge': 'Ознакомиться',
      'acknowledged': 'Ознакомлено',
      'ruleAcknowledged': 'Вы подтвердили ознакомление с этим правилом.',
      'rulesLoadFailed': 'Не удалось загрузить правила. Попробуйте ещё раз.',
      'rulesSubtitle': 'Стандарты преподавания, поведения и безопасности.',
      'settings': 'Настройки',
      'appearance': 'Оформление',
      'language': 'Язык',
      'theme': 'Тема',
      'system': 'Системная',
      'light': 'Светлая',
      'dark': 'Тёмная',
      'accentColor': 'Цвет акцента',
      'defaultShift': 'Смена по умолчанию',
      'morningShift': 'Утро · 08:00–14:00',
      'afternoonShift': 'День · 14:00–20:00',
      'fullDayShift': 'Полный день · 09:00–18:00',
      'notifications': 'Уведомления',
      'markAllRead': 'Отметить всё прочитанным',
      'notificationsEmpty': 'Всё просмотрено',
      'notificationsEmptyBody':
          'Важные обновления и напоминания появятся здесь.',
      'notificationsLoadFailed':
          'Не удалось загрузить уведомления. Попробуйте ещё раз.',
      'notificationsLoadFailedBody':
          'Ваши обновления в безопасности. Проверьте подключение и обновите страницу, когда будете готовы.',
      'notificationsStale': 'Показаны последние загруженные уведомления.',
      'lastUpdatedAt': 'Обновлено {time}',
      'notificationReadSaveFailed':
          'Уведомление открылось, но статус прочтения не сохранился.',
      'close': 'Закрыть',
      'lessonReminders': 'Напоминания об уроках',
      'privacyRoleVisibility': 'Доступ по роли',
      'privacyRoleVisibilityBody':
          'Вы видите только сведения, необходимые для назначенной работы.',
      'privacyProtectedContent': 'Защищённые учебные материалы',
      'privacyProtectedContentBody':
          'Материалы только для просмотра остаются в приложении, имеют водяной знак с вашими данными и используют защиту захвата экрана, если устройство её поддерживает.',
      'privacyAccountability': 'Ответственность',
      'privacyAccountabilityBody':
          'Действия с конфиденциальными данными защищены и учитываются.',
      'accentOption': 'Акцентный цвет: {color}',
      'accentindigo': 'Сарой',
      'accentocean': 'Марварид',
      'accentcoral': 'Самарканд',
      'accentforest': 'Дарё',
      'accentazure': 'Осмон',
      'accentamber': 'Учкун',
      'accentheritage': 'Мерос',
      'security': 'Безопасность',
      'changePassword': 'Изменить пароль',
      'editName': 'Изменить имя',
      'editProfile': 'Изменить профиль',
      'firstName': 'Имя',
      'middleName': 'Отчество',
      'lastName': 'Фамилия',
      'openSettings': 'Открыть настройки',
      'newName': 'Отображаемое имя',
      'about': 'О Starforge Staff',
      'version': 'Версия 1.0.0 (1)',
      'versionValue': 'Версия {version}',
      'signOut': 'Выйти',
      'signOutConfirm': 'Вы уверены, что хотите выйти?',
      'cancel': 'Отмена',
      'confirm': 'Да',
      'emptyTitle': 'Здесь пока пусто',
      'emptyBody': 'Когда появится что-то важное, вы увидите это здесь.',
      'actionUnavailable':
          'Эта функция пока недоступна для вашей учётной записи.',
      'workspace': 'Рабочее пространство',
      'studio': 'Медиа-студия',
      'frontDesk': 'Ресепшен',
      'leads': 'Лиды',
      'finance': 'Финансы',
      'overview': 'Обзор',
      'todaysFocus': 'Главное сегодня',
      'pending': 'Ожидает',
      'urgent': 'Срочно',
      'queue': 'Очередь',
      'newItem': 'Новая запись',
      'roleReady': 'Ваше рабочее пространство готово.',
      'openTasksCountOne': '{count} открытая задача',
      'openTasksCountFew': '{count} открытые задачи',
      'openTasksCountMany': '{count} открытых задач',
      'unreadCountOne': '{count} непрочитанный диалог',
      'unreadCountFew': '{count} непрочитанных диалога',
      'unreadCountMany': '{count} непрочитанных диалогов',
      'studentsCountOne': '{count} ученик',
      'studentsCountFew': '{count} ученика',
      'studentsCountMany': '{count} учеников',
      'groupsCountOne': '{count} назначенная группа',
      'groupsCountFew': '{count} назначенные группы',
      'groupsCountMany': '{count} назначенных групп',
      'lessonsCountOne': '{count} занятие',
      'lessonsCountFew': '{count} занятия',
      'lessonsCountMany': '{count} занятий',
      'examsCountOne': '{count} экзамен',
      'examsCountFew': '{count} экзамена',
      'examsCountMany': '{count} экзаменов',
      'pointsCountOne': '{count} балл',
      'pointsCountFew': '{count} балла',
      'pointsCountMany': '{count} баллов',
      'pagesCountOne': '{count} страница',
      'pagesCountFew': '{count} страницы',
      'pagesCountMany': '{count} страниц',
      'copiesCountOne': '{count} копия',
      'copiesCountFew': '{count} копии',
      'copiesCountMany': '{count} копий',
      'attendancePercent': 'Посещаемость: {percent}%',
    },
    'uz': {
      'appName': 'Starforge Staff',
      'welcomeBack': 'Xush kelibsiz',
      'loginSubtitle': 'Sokin va tartibli ish makoningiz.',
      'loginEyebrow': 'XODIMLAR ISH MAYDONI',
      'loginPromise': 'Aniq rejalang. Ishonch bilan o‘rgating.',
      'loginDetail':
          'Darslar, o‘quvchilar, vazifalar va suhbatlar — kuningiz uchun puxta tartiblangan.',
      'username': 'Foydalanuvchi nomi',
      'password': 'Parol',
      'usernameRequired': 'Foydalanuvchi nomini kiriting.',
      'passwordTooShort': 'Parol kamida 4 ta belgidan iborat bo‘lishi kerak.',
      'passwordRequired': 'Parolni kiriting.',
      'showPassword': 'Parolni ko‘rsatish',
      'hidePassword': 'Parolni yashirish',
      'signIn': 'Kirish',
      'forgotPassword': 'Parolni unutdingizmi?',
      'forgotMessage':
          'Iltimos, ma’muriyatga murojaat qiling. Ular parolingizni xavfsiz tiklab beradi.',
      'privacyPolicy': 'Maxfiylik siyosati',
      'viewFullPolicy': 'To‘liq siyosatni ko‘rish',
      'policyOpenFailed':
          'Siyosatni xavfsiz ochib bo‘lmadi. Qayta urinib ko‘ring.',
      'terms': 'Xodimlar maxfiyligi va shartlari',
      'termsBody':
          'Starforge xodimlar va o‘quvchilar ma’lumotlarini himoya qiladi. Kirish huquqi lavozimga bog‘liq, amallar qayd etilishi mumkin va ta’lim ma’lumotlari faqat markaz tasdiqlagan ishlar uchun ishlatiladi.',
      'role': 'Xodim lavozimi',
      'teacher': 'O‘qituvchi',
      'assistant': 'Yordamchi',
      'media': 'Media xodimi',
      'reception': 'Qabulxona',
      'sales': 'Sotuv bo‘limi',
      'printer': 'Chop etish xodimi',
      'cashier': 'Kassir',
      'staffMember': 'Xodim',
      'invalidLogin': 'Foydalanuvchi nomi yoki parol noto‘g‘ri.',
      'restrictedLogin':
          'Rahbarlar Starforge Management ilovasidan foydalanadi.',
      'loginUnavailable':
          'Hozir tizimga kirib bo‘lmadi. Internet aloqasini tekshirib, qayta urinib ko‘ring.',
      'loginRateLimited':
          'Bir necha marta urinish bo‘ldi. Biroz kutib, qayta urinib ko‘ring.',
      'roleAuto': 'Ish maydoni xodim hisobingizga moslanadi',
      'secureWorkspace': 'Xodimlar uchun yopiq ish maydoni',
      'passwordRequiredTitle': 'Yangi parol yarating',
      'passwordRequiredBody':
          'Xavfsizligingiz uchun davom etishdan oldin yangi parol tanlang.',
      'currentPassword': 'Joriy parol',
      'newPassword': 'Yangi parol',
      'confirmPassword': 'Yangi parolni takrorlang',
      'updatePassword': 'Parolni yangilash',
      'passwordRules': 'Kamida 10 ta belgidan foydalaning.',
      'passwordMismatch': 'Yangi parollar bir xil emas.',
      'passwordUpdateFailed':
          'Parolni yangilab bo‘lmadi. Joriy parolni tekshirib, qayta urinib ko‘ring.',
      'passwordUpdated': 'Parolingiz yangilandi.',
      'changesSaved': 'O‘zgarishlaringiz saqlandi.',
      'changesCouldNotSave':
          'O‘zgarishlarni saqlab bo‘lmadi. Qayta urinib ko‘ring.',
      'warmLogin':
          'Sizni ko‘rganimizdan xursandmiz. Samarali kun uchun hammasi tayyor.',
      'home': 'Asosiy',
      'groups': 'Guruhlar',
      'tasks': 'Vazifalar',
      'messages': 'Xabarlar',
      'profile': 'Profil',
      'workHub': 'Ish',
      'workHubTitle': 'To‘liq ish maydoningiz',
      'workHubSubtitle':
          'O‘quvchilar, kutubxona, so‘rovnomalar, so‘rovlar, yutuqlar, hisobotlar va profil.',
      'workNowTitle': 'E’tibor talab qiladi',
      'workResourcesTitle': 'Vositalar va yozuvlar',
      'workAccountTitle': 'Ish va hisob',
      'assignedStudents': 'O‘quvchilarim',
      'assignedStudentsSubtitle':
          'Faqat sizga biriktirilgan guruh o‘quvchilari.',
      'formsSurveys': 'Shakllar va so‘rovnomalar',
      'formsSurveysSubtitle': 'Sizga yuborilgan so‘rovnomalarga javob bering.',
      'requests': 'So‘rovlar',
      'requestsSubtitle': 'Ish bo‘yicha so‘rovlarni yarating va kuzating.',
      'achievements': 'Yutuqlar',
      'achievementsSubtitle': 'Guruhlaringizdagi o‘quvchilarni taqdirlang.',
      'reports': 'Hisobotlar',
      'reportsSubtitle': 'O‘quv hisobotlarini tayyorlang va yuboring.',
      'goodMorning': 'Xayrli tong',
      'goodAfternoon': 'Xayrli kun',
      'goodEvening': 'Xayrli kech',
      'motivation1': 'Har kungi kichik qadamlar katta mahoratga aylanadi.',
      'motivation2':
          'Sizning e’tiboringiz o‘quvchining butun kunini o‘zgartirishi mumkin.',
      'motivation3': 'Aniq o‘rgating. Mehr bilan yetaklang.',
      'motivation4':
          'Bugun ta’limni yanada qulay qilish uchun yangi imkoniyat.',
      'today': 'Bugun',
      'yesterday': 'Kecha',
      'nextLesson': 'Keyingi dars',
      'room': 'Xona',
      'students': 'O‘quvchilar',
      'totalStudents': 'Jami o‘quvchilar',
      'attendance': 'Davomat',
      'startsIn': '{time} dan keyin boshlanadi',
      'durationHoursMinutes': '{hours} soat {minutes} daqiqa',
      'durationMinutes': '{minutes} daqiqa',
      'quickActions': 'Tezkor amallar',
      'takeAttendance': 'Davomat olish',
      'openTasks': 'Vazifalarni ochish',
      'library': 'Kutubxona',
      'printCenter': 'Chop etish',
      'important': 'Muhim',
      'meeting': 'Uchrashuv',
      'meetingsTitle': 'Uchrashuvlar',
      'meetingsSubtitle':
          'Sizga ruxsat berilgan ish doirasidagi kelgusi uchrashuvlar.',
      'meetingsEmpty': 'Kelgusi uchrashuvlar yo‘q',
      'meetingsEmptyBody':
          'Yangi takliflar rejalashtirilgach shu yerda ko‘rinadi.',
      'meetingsLoadFailed': 'Uchrashuvlarni yuklab bo‘lmadi',
      'meetingPending': 'Javobingiz kutilmoqda',
      'meetingAccepted': 'Qabul qilindi',
      'meetingDeclined': 'Rad etildi',
      'acceptMeeting': 'Qabul qilish',
      'declineMeeting': 'Rad etish',
      'meetingResponseSaved': 'Uchrashuvga javobingiz saqlandi.',
      'meetingResponseFailed': 'Uchrashuvga javobingizni saqlab bo‘lmadi.',
      'schedule': 'Bugungi jadval',
      'upcomingSchedule': 'Yaqinlashayotgan jadval',
      'upcoming': 'Oldinda',
      'openAttendance': 'Davomatni ochish',
      'noUpcomingLessons': 'Yaqinlashayotgan jadvalingiz bo‘sh',
      'noUpcomingLessonsBody':
          'Yangi darslar rejalashtirilishi bilan shu yerda ko‘rinadi.',
      'dashboardNeedsMoment': 'Ayrim yangilanishlarga yana biroz vaqt kerak.',
      'suggestion': 'Tavsiya',
      'academicDepartment': 'Ta’lim bo‘limi',
      'seeAll': 'Barchasi',
      'aiInsight': 'AI tavsiyasi',
      'aiUnavailable': 'AI qisqa tanaffusda. Iltimos, keyinroq tekshiring.',
      'aiNoRecommendations':
          'AI mavjud. Hozir siz uchun tasdiqlangan tavsiya yo‘q.',
      'aiDegraded':
          'AI odatdagidan sekinroq ishlayapti, shu sabab tavsiyalar hozircha to‘xtatilgan.',
      'aiStatusUnavailable':
          'Hozir AI holatini tekshirib bo‘lmadi. Boshqa vositalar ishlashda davom etadi.',
      'aiStatusChecking': 'AI mavjudligi tekshirilmoqda…',
      'featureAvailable': 'Mavjud',
      'featureDegraded': 'Cheklangan',
      'featureUnavailable': 'Tanaffusda',
      'featureStatusUnknown': 'Holat aniqlanmoqda',
      'featureUnavailablePolite':
          'Bu bo‘lim qisqa tanaffusda. Iltimos, birozdan keyin qayta tekshiring.',
      'weeklyPulse': 'Haftalik natija',
      'lessons': 'Darslar',
      'completed': 'Bajarildi',
      'onTime': 'O‘z vaqtida',
      'reviewsDue': 'Tekshirish kerak',
      'announcements': 'E’lonlar',
      'noAnnouncements': 'Hozircha e’lonlar yo‘q.',
      'yourGroups': 'Sizning guruhlaringiz',
      'groupsSubtitle': 'Faqat sizga biriktirilgan guruhlar ko‘rsatiladi.',
      'searchGroups': 'Guruhlarni qidirish',
      'assignedGroups': 'Biriktirilgan guruhlar',
      'groupPortfolio': 'O‘quv guruhi',
      'capacity': 'Sig‘im',
      'refresh': 'Yangilash',
      'tryAgain': 'Qayta urinish',
      'search': 'Qidirish',
      'clear': 'Tozalash',
      'noItems': 'Bu yerda hozircha hech narsa yo‘q',
      'noAssignedGroups': 'Keyingi qadamlar uchun tayyor joy',
      'noAssignedGroupsBody':
          'Sizga biriktirilgan guruhlar tayyor bo‘lishi bilan shu yerda ko‘rinadi.',
      'groupsLoadFailed': 'Guruhlar uchun biroz vaqt kerak',
      'groupsLoadFailedBody':
          'Internet aloqasini tekshirib, yana bir bor urinib ko‘ring.',
      'studentListPreparing': 'Eng so‘nggi sinf ro‘yxati tayyorlanmoqda',
      'noStudentsYet': 'Yangi sinf ro‘yxati',
      'noStudentsYetBody':
          'Ushbu guruhga yozilgan o‘quvchilar shu yerda ko‘rinadi.',
      'attendanceNotMarked': 'Bu oyda davomat hali belgilanmagan',
      'groupDetailsNeedMoment': 'Ayrim guruh ma’lumotlariga biroz vaqt kerak.',
      'descriptionRequired': 'Qisqa izoh kiriting.',
      'requestCouldNotSend':
          'Bu hisobdan so‘rov yuborib bo‘lmadi. Koordinatoringizga murojaat qiling.',
      'active': 'Faol',
      'course': 'Kurs',
      'month': 'Oy',
      'studyMonthValue': '{month}-oy',
      'studyMonthRange': '1 dan 600 gacha bo‘lgan oyni kiriting.',
      'level': 'Daraja',
      'mainTeacher': 'Asosiy o‘qituvchi',
      'branch': 'Filial',
      'currentBranch': 'Hozirgi filial',
      'destinationBranch': 'Yangi filial',
      'moveGroupBranch': 'Guruhni boshqa filialga ko‘chirish',
      'moveStudentBranch': 'O‘quvchini boshqa filialga ko‘chirish',
      'transferReason': 'Ko‘chirish sababi',
      'transferReasonHint': 'Qisqa ish sababini kiriting',
      'transferImpact': 'Nimalar o‘zgaradi',
      'groupTransferImpact':
          'Faol o‘quvchilar guruh bilan birga ko‘chadi. Yangi filial xavfsiz sozlashi uchun o‘qituvchilar, xona va kelajak darslar tozalanadi.',
      'studentTransferImpact':
          'O‘quvchi yangi filialga o‘tadi va hozirgi guruhidan chiqariladi. Hisobi va o‘qish tarixi saqlanadi.',
      'confirmTransferImpact':
          'Bu o‘zgarishlarni ko‘rib chiqdim va tasdiqlayman',
      'transferAuditNotice':
          'Ko‘chirish ijrochi va sabab bilan doimiy tarixga yoziladi.',
      'confirmBranchTransfer': 'Filialga ko‘chirishni tasdiqlash',
      'movingBranch': 'Ko‘chirilmoqda…',
      'transferComplete': 'Filialga ko‘chirish yakunlandi.',
      'transferCouldNotComplete':
          'Ko‘chirishni yakunlab bo‘lmadi. Ma’lumotlarni tekshirib, qayta urinib ko‘ring.',
      'branchesLoadFailed': 'Filiallar ro‘yxatiga biroz vaqt kerak.',
      'noTransferBranches': 'Boshqa faol filial mavjud emas.',
      'department': 'Bo‘lim',
      'mainRoom': 'Asosiy xona',
      'lessonCycle': 'Darslar sikli',
      'lessonCycleShort': '{count} dars',
      'cycleProgress': '{total} darsdan {completed} tasi yakunlangan',
      'cycleOverallProgress': 'Jami {count} ta dars yakunlangan',
      'cycleNextLesson': 'Sikldagi keyingi dars: {number}',
      'cycleLessonsRemainingOther': 'Imtihongacha {count} ta dars',
      'cycleExamDue': 'Keyingi yakunlanadigan dars — imtihon darsi',
      'cycleExamDueBody':
          'Imtihon guruh uchun belgilangan darslar sikliga kiradi. Yaqin darsni tekshirib, baholashga tayyorlaning.',
      'cycleCompletionIncomplete': 'Jadvalga ozgina e’tibor kerak',
      'cycleCompletionIncompleteBody':
          'O‘tgan rejalashtirilgan darslardan {count} tasining yakunlangan holati belgilanmagan. Faqat tasdiqlangan yakuniy darslar hisoblanadi.',
      'cycleIncompleteOther':
          'O‘tgan {count} ta darsning yakunlangan holati belgilanmagan. Faqat tasdiqlangan darslar hisoblanadi.',
      'cycleLevelManual':
          'Natijalar tayyor bo‘lgach, daraja o‘zgarishini ta’lim jamoasi tasdiqlaydi.',
      'cycleUnavailable': 'Sikl holati hozircha yuklanmadi',
      'cycleUnavailableBody':
          'Guruhdan foydalanish mumkin. Yangilash uchun pastga tortib, yana tekshiring.',
      'groupSummary': 'Guruh xulosasi',
      'studentList': 'O‘quvchilar ro‘yxati',
      'history': 'Tarix',
      'exams': 'Imtihonlar',
      'viewProfile': 'Profilni ko‘rish',
      'call': 'Qo‘ng‘iroq',
      'message': 'Xabar',
      'requestAction': 'So‘rov yuborish',
      'requestMove': 'Ko‘chirish so‘rovi',
      'requestHelp': 'Yordam so‘rovi',
      'requestKick': 'Chetlatish so‘rovi',
      'requestReason': 'Vaziyatni aniq tushuntiring',
      'sendRequest': 'So‘rovni yuborish',
      'requestSent': 'So‘rovingiz mas’ul jamoaga yuborildi.',
      'contactGuardian': 'Vasiy',
      'phone': 'Telefon',
      'dateOfBirth': 'Tug‘ilgan sana',
      'joined': 'Qo‘shilgan sana',
      'notes': 'Ta’lim qaydlari',
      'studentNotesUnavailable':
          'Bu o‘quvchi uchun hali ta’lim qaydlari ulashilmagan.',
      'studentOverview': 'O‘quvchi haqida',
      'academicLevel': 'Akademik daraja',
      'email': 'Elektron pochta',
      'location': 'Manzil',
      'previousSchool': 'Oldingi maktab',
      'attendanceSummary': 'Davomat xulosasi',
      'recentResults': 'So‘nggi natijalar',
      'familyContacts': 'Oila kontaktlari',
      'assignmentsSummary': 'Topshiriqlar xulosasi',
      'assigned': 'Biriktirilgan',
      'open': 'Ochiq',
      'noFamilyContacts': 'Oila kontaktlari hali qo‘shilmagan.',
      'attendanceHistory': 'Davomat tarixi',
      'lessonHistory': 'Darslar tarixi',
      'previousMonth': 'Oldingi oy',
      'nextMonth': 'Keyingi oy',
      'present': 'Keldi',
      'absent': 'Kelmadi',
      'late': 'Kechikdi',
      'excused': 'Sababli',
      'smartCard': 'Smart karta',
      'warningCard': 'Ogohlantirish',
      'noCard': 'Kartasiz',
      'feedbackCard': 'Dars kartasi',
      'skillBreakdown': 'Koʻnikmalar boʻyicha natija',
      'overallScore': 'Umumiy ball',
      'startAttendance': 'Bugungi davomatni boshlash',
      'saveAttendance': 'Davomatni saqlash',
      'attendanceSaved': 'Davomat muvaffaqiyatli saqlandi.',
      'attendanceSaveFailed':
          'Davomatni saqlab bo‘lmadi. Ma’lumotlarni tekshirib, qayta urinib ko‘ring.',
      'attendanceStartsAt': 'Davomat {time} da ochiladi',
      'attendanceOpensIn': 'Davomat {time} dan keyin ochiladi',
      'unmarked': 'Belgilanmagan',
      'studentsStillUnmarked': 'Yana {count} o‘quvchi belgilanmagan.',
      'unsavedAttendanceTitle': 'Saqlamasdan chiqilsinmi?',
      'unsavedAttendanceBody': 'Davomatdagi o‘zgarishlar hali saqlanmadi.',
      'continueEditing': 'Davom etish',
      'discardChanges': 'O‘zgarishlarni bekor qilish',
      'showingPreviousData':
          'Yangilab bo‘lmadi. Oldingi davomat ma’lumotlari ko‘rsatilmoqda.',
      'scheduled': 'Rejalashtirilgan',
      'registerIncomplete': 'Ro‘yxat to‘liq emas',
      'registerComplete': 'Ro‘yxat to‘liq',
      'fullMonthView': 'To‘liq oy',
      'tapDayToFilter': 'Dars kunini ochish uchun ustiga bosing',
      'showAll': 'Barchasini ko‘rsatish',
      'markedLessons': 'Belgilangan',
      'absences': 'Yo‘qlamalar',
      'attendanceViewOnly': 'Bu hisob uchun davomat faqat ko‘rish rejimida',
      'noLessonsThisPeriod': 'Taqvimning sokin qismi',
      'noLessonsThisPeriodBody':
          'Tanlangan davrda rejalashtirilgan darslar yo‘q.',
      'attendanceNeedMoment': 'Davomatga yana biroz vaqt kerak',
      'examsNeedMoment': 'Imtihonlar tarixiga yana biroz vaqt kerak',
      'noExamsYet': 'Keyingi marralar shu yerdan boshlanadi',
      'noExamsYetBody': 'Imtihonlar tayyor bo‘lganda shu yerda ko‘rinadi.',
      'examHistoryHint':
          'Butun guruhning e’lon qilingan ballarini ko‘rish uchun imtihonni oching.',
      'points': 'Ball',
      'published': 'E’lon qilingan',
      'resultsPending': 'Natijalar kutilmoqda',
      'resultsViewLimited':
          'Batafsil natijalar vakolatli o‘qituvchilar uchun mavjud.',
      'resultsNeedMoment':
          'Natijalarga yana biroz vaqt kerak. Qayta urinib ko‘ring.',
      'allPresent': 'Barchasi keldi',
      'lesson': 'Dars',
      'examDay': 'Imtihon kuni',
      'autoExamNote':
          '12-dars avtomatik ravishda daraja imtihoni sifatida belgilanadi.',
      'examHistory': 'Imtihonlar tarixi',
      'passed': 'O‘tdi',
      'needsRetry': 'Qayta topshiradi',
      'listening': 'Tinglash',
      'reading': 'O‘qish',
      'writing': 'Yozish',
      'speaking': 'Gapirish',
      'updateProgress': 'Oy va darajani yangilash',
      'save': 'Saqlash',
      'myTasks': 'Mening vazifalarim',
      'assignedToMe': 'Menga berilgan',
      'createdByMe': 'Men yaratgan',
      'board': 'Doska',
      'tasksNeedMoment': 'Vazifalaringizga yana biroz vaqt kerak',
      'tasksShowingPrevious':
          'Yangilab bo‘lmadi. Oldingi vazifalar ro‘yxati ko‘rsatilmoqda.',
      'taskMoveFailed': 'Vazifani ko‘chirib bo‘lmadi. Qayta urinib ko‘ring.',
      'taskCreateFailed': 'Vazifani yaratib bo‘lmadi. Qayta urinib ko‘ring.',
      'taskTitleRequired': 'Vazifa nomini kiriting.',
      'noDueDate': 'Muddat belgilanmagan',
      'list': 'Ro‘yxat',
      'toDo': 'Bajarish kerak',
      'inProgress': 'Jarayonda',
      'blocked': 'To‘xtatilgan',
      'done': 'Tayyor',
      'cancelled': 'Bekor qilingan',
      'taskViewOnly': 'Bu vazifani faqat ijrochi o‘zgartira oladi.',
      'highPriority': 'Yuqori muhimlik',
      'dueToday': 'Bugun',
      'addTask': 'Yangi vazifa',
      'taskTitle': 'Vazifa nomi',
      'description': 'Tavsif',
      'dueDate': 'Muddat',
      'createTask': 'Vazifa yaratish',
      'taskCreated': 'Vazifa yaratildi.',
      'inbox': 'Kiruvchi',
      'archived': 'Arxiv',
      'searchMessages': 'Suhbatlarni qidirish',
      'newConversation': 'Yangi suhbat',
      'staff': 'Xodimlar',
      'sendMessage': 'Xabar',
      'typeMessage': 'Xabar…',
      'online': 'Onlayn',
      'recentlyActive': 'Yaqinda faol bo‘lgan',
      'voiceMessage': 'Ovozli xabar',
      'holdToRecordVoice': 'Ovozli xabar yozish uchun bosib turing',
      'microphonePermissionNeeded':
          'Ovozli xabar yozish uchun mikrofonga ruxsat bering.',
      'voiceRecordingFailed':
          'Ovozli xabarni yozib bo‘lmadi. Yana urinib ko‘ring.',
      'voiceMessageTooShort': 'Xabar yozish uchun biroz uzoqroq bosib turing.',
      'archiveConversation': 'Suhbatni arxivlash',
      'unarchiveConversation': 'Suhbatni kiruvchilarga qaytarish',
      'conversationArchived': 'Suhbat arxivlandi.',
      'movedToInbox': 'Suhbat kiruvchilarga qaytarildi.',
      'resourceAudience': 'Tasdiqlangach, kimlar ko‘ra oladi?',
      'ownStudentsAudience': 'Mening o‘quvchilarim',
      'globalAudience': 'Barcha foydalanuvchilar',
      'audienceLocationUnavailable':
          'Bu auditoriya uchun hozircha ruxsat etilgan joy yo‘q.',
      'allowDownloads': 'Yuklab olishga ruxsat',
      'allowDownloadsBody': 'Tasdiqlangan foydalanuvchilar nusxa saqlay oladi.',
      'viewOnlyBody':
          'Tasdiqlangan foydalanuvchilar uni faqat Starforge ichida ochadi.',
      'unsupportedAttachmentFormat':
          'Rasm uchun JPG, PNG yoki WEBP, video uchun MP4, audio uchun MP3 tanlang.',
      'recording': 'Yozilmoqda… yuborish uchun qo‘yib yuboring',
      'mediaSent': 'Media yuborishga tayyor.',
      'unread': 'o‘qilmagan',
      'conversation': 'Suhbat',
      'openConversation': 'Suhbatni ochish',
      'conversationUnavailable':
          'Bu suhbat hozircha ochilmadi. Iltimos, yana urinib ko‘ring.',
      'noContacts': 'Hozircha hech kim yo‘q',
      'noContactsBody':
          'Xabar yozishingiz mumkin bo‘lgan o‘quvchi va xodimlar shu yerda chiqadi.',
      'noConversations': 'Xabarlar oynasi sokin',
      'noConversationsBody':
          'O‘quvchingiz yoki hamkasbingiz bilan yangi suhbat boshlang.',
      'noMessages': 'Yangi suhbat',
      'noMessagesBody': 'Tayyor bo‘lsangiz, birinchi bo‘lib salom yozing.',
      'messagesLoadFailed': 'Suhbatlar uchun yana bir zum kerak',
      'messagesLoadFailedBody':
          'Internet aloqasini tekshirib, yana urinib ko‘ring.',
      'messageSendFailed': 'Xabar yuborilmadi. Matningiz shu yerda saqlandi.',
      'messageAttachmentFailed':
          'Faylni yuborib bo‘lmadi. Iltimos, yana urinib ko‘ring.',
      'readOnlyConversation': 'Bu suhbatni o‘qishingiz mumkin.',
      'attachment': 'Ilova',
      'camera': 'Kamera',
      'gallery': 'Galereya',
      'audio': 'Audio',
      'file': 'Fayl',
      'librarySubtitle': 'Kitoblar, audio va video darslar bir qulay joyda.',
      'awaitingTeacherApproval': 'O‘qituvchi tekshiruvi',
      'awaitingPublication': 'Yakuniy tekshiruv',
      'approveResource': 'Materialni tasdiqlash',
      'resourceApproved': 'Material yakuniy tekshiruvga yuborildi.',
      'resourceApprovalFailed': 'Bu materialni tasdiqlab bo‘lmadi.',
      'downloadResource': 'Yuklab olish',
      'searchLibrary': 'Kutubxonadan qidirish',
      'all': 'Barchasi',
      'books': 'Kitoblar',
      'playlists': 'Pleylistlar',
      'podcasts': 'Podkastlar',
      'videos': 'Videolar',
      'recentlyAdded': 'Yaqinda qo‘shilgan',
      'popularPlaylists': 'Tanlangan pleylistlar',
      'upload': 'Yuklash',
      'uploadResource': 'Material yuklash',
      'resourceTitle': 'Material nomi',
      'audience': 'Auditoriya',
      'everyone': 'Barchaga',
      'myStudents': 'Faqat o‘quvchilarimga',
      'allowDownload': 'Yuklab olishga ruxsat',
      'protectedContent':
          'Faqat ko‘rish: yuklab olish mavjud emas va shaxsingiz belgilanadi.',
      'protectedWatermark': 'Ko‘ruvchi: {identity}',
      'chooseFile': 'Fayl tanlash',
      'publish': 'Nashr qilish',
      'uploadReady': 'Material nashr qilish uchun tayyorlandi.',
      'resources': 'ta material',
      'contentLocation': 'Kutubxona jildi',
      'resourceReviewNote':
          'Material ko‘rinishidan oldin tekshiriladi. Auditoriya va yuklab olish huquqi tanlangan kutubxona qoidalariga bog‘liq.',
      'noUploadLocation':
          'Bu hisob uchun hozircha kutubxona jildi mavjud emas.',
      'uploadSubmitted': 'Material yuklandi va tayyorlanmoqda.',
      'uploadFailed': 'Materialni yuklab bo‘lmadi. Yana urinib ko‘ring.',
      'uploading': 'Yuklanmoqda…',
      'resourceBeingPrepared':
          'Bu material hali tayyorlanmoqda. Birozdan so‘ng tekshiring.',
      'resourceUnavailable':
          'Bu material hozircha mavjud emas. Keyinroq urinib ko‘ring.',
      'rejected': 'Tuzatish kerak',
      'draft': 'Qoralama',
      'statusOpen': 'Ochiq',
      'statusClosed': 'Yopilgan',
      'statusIssued': 'Chiqarilgan',
      'statusPartiallyPaid': 'Qisman to‘langan',
      'statusPaid': 'To‘langan',
      'statusVoid': 'Bekor qilingan',
      'statusOverdue': 'Muddati o‘tgan',
      'statusPending': 'Qayta ishlanmoqda',
      'statusClean': 'Tayyor',
      'starforgeLibrary': 'Starforge kutubxonasi',
      'libraryLoadFailed': 'Kutubxona uchun yana bir zum kerak',
      'libraryLoadFailedBody':
          'Internet aloqasini tekshirib, yana urinib ko‘ring.',
      'openResource': 'Materialni ochish',
      'availablePrinters': 'Mavjud printerlar',
      'printerSubtitle': 'Xavfsiz chop etishni sozlang yoki rejalashtiring.',
      'available': 'Mavjud',
      'busy': 'Band',
      'paper': 'Qog‘oz',
      'copies': 'Nusxalar',
      'color': 'Rangli',
      'blackWhite': 'Oq-qora',
      'doubleSided': 'Ikki tomonlama',
      'schedulePrint': 'Rejalashtirish',
      'printNow': 'Hozir chop etish',
      'selectMaterial': 'Material tanlash',
      'fromLibrary': 'Kutubxonadan',
      'fromDevice': 'Qurilmadan',
      'scheduledJobs': 'Rejalashtirilgan ishlar',
      'printQueued': 'Chop etish ishi navbatga qo‘shildi.',
      'jobScheduled': 'Chop etish rejalashtirildi.',
      'printLibrarySourceNote':
          'Tayyor topshiriq, hisobot, chek va qaydnomalarni chop etish mumkin.',
      'printRequestUnavailable':
          'Bu hujjat xavfsiz chop etish uchun hali tayyor emas.',
      'printFileUnsupported':
          'Qurilmadan PDF, JPEG, PNG yoki WebP faylini tanlang.',
      'printLibraryTitle': 'Kutubxonadan tanlash',
      'noPrintableMaterials': 'Chop etiladigan material yo‘q',
      'noPrintableMaterialsBody':
          'Yuklab olishga ruxsat berilgan PDF va rasmlar shu yerda chiqadi.',
      'decreaseCopies': 'Nusxalar sonini kamaytirish',
      'increaseCopies': 'Nusxalar sonini oshirish',
      'printScheduleFuture': 'Kelajakdagi vaqtni tanlang.',
      'printSubmitFailed':
          'Chop etish ishini yuborib bo‘lmadi. Materialni tekshirib, yana urinib ko‘ring.',
      'submittingPrint': 'Yuborilmoqda…',
      'printerOffline': 'Oflayn',
      'noPrinters': 'Filialingizda hozircha mavjud printer yo‘q.',
      'readyToConfigure': 'Sozlashga tayyor',
      'printerReady': 'Chop etishga tayyor',
      'noPrintJobs': 'Chop etish ishlari hozircha yo‘q',
      'noPrintJobsBody': 'Chop etish tarixi shu yerda ko‘rinadi.',
      'queued': 'Navbatda',
      'picked': 'Qabul qilindi',
      'printing': 'Chop etilmoqda',
      'failed': 'E’tibor kerak',
      'needsReview': 'Tekshirish kerak',
      'assignment': 'Topshiriq',
      'transcript': 'Qaydnoma',
      'report': 'Hisobot',
      'receipt': 'Chek',
      'document': 'Hujjat',
      'pages': 'bet',
      'workingSince': 'Ish boshlagan sana',
      'salaryHistory': 'Maosh tarixi',
      'salaryCurrent': 'Joriy maosh',
      'salaryPrivate':
          'Shaxsiy ish ma’lumotlari faqat siz va vakolatli moliya xodimlariga ko‘rinadi.',
      'noPayslips': 'Hisob varaqalari hali yo‘q',
      'noPayslipsBody':
          'Tasdiqlangan hisob varaqalari mavjud bo‘lganda shu yerda chiqadi.',
      'payslipPaid': 'To‘langan',
      'payslipPending': 'Kutilmoqda',
      'employmentDataUnavailable': 'Ish ma’lumotlari mavjud emas',
      'employmentDataUnavailableBody':
          'Tasdiqlangan ish ma’lumoti kerak bo‘lsa, ma’muriyatga murojaat qiling.',
      'contract': 'Shartnoma',
      'contractUnavailable': 'Shartnoma mavjud emas',
      'contractUnavailableBody':
          'Tasdiqlangan shartnoma ma’muriyat e’lon qilganda shu yerda chiqadi.',
      'employment': 'Mehnat ma’lumotlari',
      'stats': 'Ish statistikasi',
      'years': 'yil',
      'rating': 'Reyting',
      'rules': 'O‘quv markazi qoidalari',
      'rulesRequired': 'Majburiy standart',
      'ruleVersion': 'Siyosat versiyasi',
      'acknowledge': 'Tanishib chiqdim',
      'acknowledged': 'Tanishilgan',
      'ruleAcknowledged': 'Ushbu qoida bilan tanishganingiz tasdiqlandi.',
      'rulesLoadFailed': 'Qoidalarni yuklab bo‘lmadi. Yana urinib ko‘ring.',
      'rulesSubtitle': 'Dars, xodimlar odobi va xavfsizlik standartlari.',
      'settings': 'Sozlamalar',
      'appearance': 'Ko‘rinish',
      'language': 'Til',
      'theme': 'Mavzu',
      'system': 'Tizim',
      'light': 'Yorug‘',
      'dark': 'Qorong‘i',
      'accentColor': 'Asosiy rang',
      'defaultShift': 'Standart smena',
      'morningShift': 'Ertalab · 08:00–14:00',
      'afternoonShift': 'Kunduzgi · 14:00–20:00',
      'fullDayShift': 'To‘liq kun · 09:00–18:00',
      'notifications': 'Bildirishnomalar',
      'markAllRead': 'Barchasini o‘qilgan deb belgilash',
      'notificationsEmpty': 'Hammasi ko‘rib chiqildi',
      'notificationsEmptyBody':
          'Muhim yangiliklar va eslatmalar shu yerda chiqadi.',
      'notificationsLoadFailed':
          'Bildirishnomalarni yuklab bo‘lmadi. Yana urinib ko‘ring.',
      'notificationsLoadFailedBody':
          'Yangiliklaringiz saqlanadi. Ulanishni tekshirib, tayyor bo‘lganda yangilang.',
      'notificationsStale': 'Oxirgi yuklangan bildirishnomalar ko‘rsatilmoqda.',
      'lastUpdatedAt': 'Oxirgi yangilanish: {time}',
      'notificationReadSaveFailed':
          'Bildirishnoma ochildi, ammo o‘qilgan holatini saqlab bo‘lmadi.',
      'close': 'Yopish',
      'lessonReminders': 'Dars eslatmalari',
      'privacyRoleVisibility': 'Lavozimga mos ko‘rinish',
      'privacyRoleVisibilityBody':
          'Siz faqat biriktirilgan ishingiz uchun kerakli ma’lumotlarni ko‘rasiz.',
      'privacyProtectedContent': 'Himoyalangan o‘quv materiallari',
      'privacyProtectedContentBody':
          'Faqat ko‘rish uchun materiallar ilova ichida qoladi, shaxsingiz tushirilgan suv belgisi bilan ko‘rsatiladi va qurilma qo‘llasa ekran tasvirini himoyalash vositalaridan foydalanadi.',
      'privacyAccountability': 'Mas’uliyat',
      'privacyAccountabilityBody':
          'Maxfiy amallar himoyalanadi va qayd etiladi.',
      'accentOption': '{color} asosiy rang',
      'accentindigo': 'Saroy',
      'accentocean': 'Marvarid',
      'accentcoral': 'Samarqand',
      'accentforest': 'Daryo',
      'accentazure': 'Osmon',
      'accentamber': 'Uchqun',
      'accentheritage': 'Meros',
      'security': 'Xavfsizlik',
      'changePassword': 'Parolni o‘zgartirish',
      'editName': 'Ismni o‘zgartirish',
      'editProfile': 'Profilni o‘zgartirish',
      'firstName': 'Ism',
      'middleName': 'Otasining ismi',
      'lastName': 'Familiya',
      'openSettings': 'Sozlamalarni ochish',
      'newName': 'Ko‘rinadigan ism',
      'about': 'Starforge Staff haqida',
      'version': 'Versiya 1.0.0 (1)',
      'versionValue': 'Versiya {version}',
      'signOut': 'Chiqish',
      'signOutConfirm': 'Haqiqatan ham chiqmoqchimisiz?',
      'cancel': 'Bekor qilish',
      'confirm': 'Tasdiqlash',
      'emptyTitle': 'Bu yerda hozircha bo‘sh',
      'emptyBody':
          'E’tiboringiz kerak bo‘lganda, ma’lumot shu yerda paydo bo‘ladi.',
      'actionUnavailable':
          'Bu imkoniyat hozircha sizning hisobingiz uchun mavjud emas.',
      'workspace': 'Ish maydoni',
      'studio': 'Media studiya',
      'frontDesk': 'Qabulxona',
      'leads': 'Mijozlar',
      'finance': 'Moliya',
      'overview': 'Umumiy ko‘rinish',
      'todaysFocus': 'Bugungi asosiy ishlar',
      'pending': 'Kutilmoqda',
      'urgent': 'Shoshilinch',
      'queue': 'Navbat',
      'newItem': 'Yangi yozuv',
      'roleReady': 'Lavozimingiz uchun ish maydoni tayyor.',
      'openTasksCountOther': '{count} ta ochiq vazifa',
      'unreadCountOther': '{count} ta o‘qilmagan suhbat',
      'studentsCountOther': '{count} nafar o‘quvchi',
      'groupsCountOther': '{count} ta biriktirilgan guruh',
      'lessonsCountOther': '{count} ta dars',
      'examsCountOther': '{count} ta imtihon',
      'pointsCountOther': '{count} ball',
      'pagesCountOther': '{count} sahifa',
      'copiesCountOther': '{count} nusxa',
      'attendancePercent': 'Davomat: {percent}%',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (supported) => supported.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).tr(key);
  String trCount(String key, int count) =>
      AppLocalizations.of(this).count(key, count);
}
